### ISSUE TITLE
integrate with travisci

### ISSUE THREAD

**Issue by dustinvtran** [blei-lab/edward#1]
https://travis-ci.org

**Comment by dustinvtran** [comment]
bump @dawenl, now that the library is public

**Comment by dawenl** [comment]
on it

**Comment by dawenl** [comment]
I added to repo to travis CI, but need to add a `.travis.yml` to inform travis how to build and test. Do we have an official dependency for edward? e.g. numpy/scipy is a must, tensorflow? pystan?

**Comment by dustinvtran** [comment]
See `setup.py` :)

**Comment by dawenl** [comment]
BTW, I created a test branch `travis_test` and feel free to add anything necessary.

**Comment by dawenl** [comment]
now we have travisCI via #94
