### ISSUE TITLE
add epsilons to perturb function arguments which error if exactly at boundary value

### ISSUE THREAD

**Issue by dustinvtran** [blei-lab/edward#121]
Define in `util.py` to get `ed.epsilon()` which returns 1e-8. Then we can use this in computations to have `tf.log(x + ed.epsilon())` in the case that `x` varies and in fact reaches 0. We should be careful about where we add these perturbations though. The SciPy-like distributions file should arguably not have any perturbations because it tries to mimick SciPy as closely as possible and SciPy doesn't do this. In the distribution objects in `variationals.py` we can perturb stuff.

**Comment by dawenl** [comment]
1e-8 seems a little bit arbitrary. `np.finfo(DTYPE).tiny` might be a better option.

**Comment by dustinvtran** [comment]
This is not necessary in the Edward code base as all parameters are written by the user. But it could be useful to add them to the various examples if helpful.
