### ISSUE TITLE
option for sparse data representation in data class

### ISSUE THREAD

**Issue by mariru** [blei-lab/edward#123]

**Comment by dawenl** [comment]
I am very interested in this as well -- and it's highly relevant to what I mostly work with. Do you have any plan on what to do? My concern is that among all the languages/frameworks that edward supports, at least tensorflow doesn't have a very good sparse support, which could be a problem.

**Comment by mariru** [comment]
I had something like this in mind:
Store the existing data as a one dimensional tensorflow tensor and also store the indices that relate this sparse representation to the dense representation which is not stored explicitly.

Then, when `data.sample()` is called it returns both a subsample of the data as well as the indices this values correspond to.

**Comment by dustinvtran** [comment]
So at the moment data is only used in the model (and mapping if the user specifies an inverse mapping for `q(z | x)` that's non-trivial). Is there a reason sparse data is not supported if the user defines both the data object and the method (`model.log_prob()`) which interfaces with the data object? Or do you mean it's non-trivial how to do data subsampling?

**Comment by dawenl** [comment]
I think the solution @mariru proposes will work with subsampling, but my concern is that it will not work when there is a need for sparse operation (e.g. matrix dot product between the sparse data and parameter) which should be pretty common.

**Comment by dawenl** [comment]
Just found out about [tf.SparseTensor](https://www.tensorflow.org/versions/r0.9/api_docs/python/sparse_ops.html), which seems a good solution to this. Anyone has any experience with it? If not, I can take a stab at it.

**Comment by dustinvtran** [comment]
Nope, and I also recommend you can take a stab at it :)

**Comment by dustinvtran** [comment]
I still think this is fine because only the user interacts explicitly with the data when they work with the `log_prob()` method in their defined model. So I'm not sure where I see the precise difficulty but maybe this will be clearer to me as you do stuff.

I do see a need for sparse tensors when dealing with sparse Distribution objects though. This will become clear after I merge #138, which lets distribution objects have arbitrary shape to represent arbitrary-sized tensors of random variables.

**Comment by dustinvtran** [comment]
closing as we no longer have a data class (nor do we hand-implement any distribution methods)
