### ISSUE TITLE
predefined toy, simulated and benchmark data

### ISSUE THREAD

**Issue by diengadji** [blei-lab/edward#125]
It would be useful to have some ready-to-use data whether it be a toy dataset, a simulated dataset or some real benchmark dataset like the ones from the UCI repository.

Toy datasets: 
currently most of the examples come with a custom build_toy_data() method. A work around this is to have a predefined toy for each type of task…
one use case would be:
from edward.datasets import load_toy_classification_data
data = load_toy_classification_data(n_classes)

Simulated datasets:
It would also be cool to be able to create some simulated data from a well documented generative process...

Benchmark datasets:
It would be nice to have some benchmark datasets from UCI preloaded and formatted for edward

**Comment by mariru** [comment]
We could make `load_[...]_data()` return an edward data object. (maybe that is exactly what you had in mind)

**Comment by diengadji** [comment]
@mariru : yes the goal is to be able to do for example 
data = load_toy_classification_data(n_classes) 
and then be able to directly feed it into
inference = ed.MFVI(model, variational, data)

**Comment by dustinvtran** [comment]
I'm in favor of NumPy arrays so the user can use the same data set outside of Edward. For example, a user wants to use a random forest classifier or clustering algorithm in scikit-learn and compare it to the hierarchical model written and inferred with Edward.

**Comment by diengadji** [comment]
the structure of the branch called datasets right now is:
    edward/datasets just like edward/models and edward/stats
    
then you have files: benchmark.py, toy.py and simulated.py

in benchmark.py we should have methods such as load_mist(), load_crabs(), load_ptb(), load_iris() etc
in toy.py we should have methods such as load_toy_classification_data()  and load_toy_regression_data() 

@dustinvtran : re Data abstraction: i think working directly with numpy arrays is a good idea as well...

**Comment by mariru** [comment]
we could just add a flag `ed_data=True/False` which can be passed to any of the load functions and if it is `True` it returns a edward object and by default is returns numpy array with data.

**Comment by dustinvtran** [comment]
Now that all Edward data objects are just dictionaries, we can easily make the return value of these `load_...()` functions be NumPy arrays, or a dictionary of NumPy arrays. This will be compatible for use both inside and outside Edward.

**Comment by dustinvtran** [comment]
Moved to https://github.com/edwardlib/observations.
