### ISSUE TITLE
pare down args and kwargs in inferences.py

### ISSUE THREAD

**Issue by akucukelbir** [blei-lab/edward#128]
some functions, like `VariationalInference.run` just pipe `*args` and `**kwargs` through to other functions.

we should clean this up.

**Comment by dustinvtran** [comment]
this one's on purpose so the same arguments used to run `inference.initialize()` (if you're manually doing a for-loop) can be done for the more automated `inference.run()`. this deals with inheritance better than manual piping: `inference.initialize()` has different arguments in each derived class and so the alternative is to rewrite `inference.run()` in the derived class each time.
