### ISSUE TITLE
stats.distributions.Distribution class never used

### ISSUE THREAD

**Issue by akucukelbir** [blei-lab/edward#131]
this class is empty, with a lot of docstring. 

we should be able to remove it once i update the docstring for all the other distributions.

(unless i'm missing something.)

**Comment by dustinvtran** [comment]
you are correct. once we have api pages where we can discuss specific concepts, we can put the general documentation describing the pattern for all classes there. See, e.g., the top description [here](http://keras.io/callbacks/) which is additional writing on top of the per-object docstrings.

**Comment by akucukelbir** [comment]
ok great.

i agree. unifying documentation can go directly into the website and we can remove it from the source.

we'll figure out the best way of doing that once we finish the doc reorganization.
