### ISSUE TITLE
stats.binom.rvs unused n parameter

### ISSUE THREAD

**Issue by akucukelbir** [blei-lab/edward#132]
```{language=Python}
class Binom:
    def rvs(self, n, p, size=1):       
        return stats.binom.rvs(p, size=size)
```

shouldn't that be `stats.binom.rvs(n, p, size=size)` ?

**Comment by dustinvtran** [comment]
Yep, good eye (it isn't used anywhere and hence wasn't a problem in any implementation examples or tests). Can you make the change and push directly to master?

**Comment by akucukelbir** [comment]
done.
