### ISSUE TITLE
rename Multivariate_Normal

### ISSUE THREAD

**Issue by akucukelbir** [blei-lab/edward#134]
All other distributions based on and/or related to Gaussians end with `norm`

i propose `Multi_Norm`

**Comment by dustinvtran** [comment]
In order to stick to current conventions, `multivariate_normal()` is the name in [SciPy](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.multivariate_normal.html). :)

**Comment by akucukelbir** [comment]
just because scipy is inconsistent, doesn't mean we have to be :)
