### ISSUE TITLE
make Distributions.log_prob(self, xs) recursive

### ISSUE THREAD

**Issue by akucukelbir** [blei-lab/edward#140]
figure out generic solution to when `len(self.shape) >= 4`

some ideas:
http://stackoverflow.com/questions/22473053/itertools-equivalent-of-nested-loop-for-x-in-xs-for-y-in-ys
http://docs.scipy.org/doc/numpy/reference/generated/numpy.nditer.html

**Comment by dustinvtran** [comment]
Solved via #237, which no longer uses such an implementation.
