### ISSUE TITLE
Feature list: Graphical Models

### ISSUE THREAD

**Issue by bhargavvader** [blei-lab/edward#154]
Hello, I noticed that graphical modeling language is a wanted feature on the feature list.
Could someone elaborate on this - what exactly is wanted? Any rough ideas of an API, or what it's supposed to do?

Any links, either academic reading or some code will be useful to start contributing. :)

Edit: I noticed the helpful links on the [Edward](http://edwardlib.org) page, but not much was said about what kind of graphical model features would be wanted.

**Comment by dustinvtran** [comment]
hi @bhargavvader. There's quite a features wanted in the graphical modeling language. For example: conditional conjugacy, Markov blankets, localized inference updates to a subset of latent variables, instantiating subgraphs, tensor operations. The modeling language touches upon much if not all of the code base. (For example, many recent pull requests such as #126, #138, #156 all make progress towards this generality.) So it may be hard to contribute to.

We have an idea of an API which we're sorting out in collaboration with a few Google Brain folks. Not sure when it'll be ready to release yet. 

If you're interested in contributing, I suggest something more bite-sized as a first step. For example: #80, #22, #35.

**Comment by bhargavvader** [comment]
Thanks for the reply @dustinvtran!

I'm currently implementing Dynamic Topic Models in python for Gensim as part of the Google Summer of Code program, and thought that if there might be an overlap and I could contribute here as well. 

I can imagine something like a graphical modeling language wouldn't be trivial at all - I'll have a look at the PRs/issues you linked to and see what's been going on. :)

**Comment by dustinvtran** [comment]
Great! We're also planning to have a topic model example as well. @dblei was just telling me the other day that there's no good scalable and robust implementation of dynamic topic models. It's one of our target goals in Edward, using SVI and other techniques.

**Comment by datnamer** [comment]
Question, is it possible to get gradients for a pure python node/variable?

**Comment by dustinvtran** [comment]
I believe it is. You have to use a TensorFlow registration mechanism to manually register the gradient.

**Comment by datnamer** [comment]
Have you seen Numpy [Autograd](https://github.com/HIPS/autograd) by @mattjj and Harvard Intelligent Probabilistic Systems Group? Maybe there is room for collaboration or integration here.

**Comment by dustinvtran** [comment]
Woah, that's an interesting point. So from my understanding TensorFlow does a mix of symbolic differentiation reverse-mode automatic differentiation based on the TensorFlow ops in the computational graph. And you're saying that for `tf.py_func` wrappers around a native Python function, we can use autodiff from a pure Python autodiffer such as autograd and then register the gradient so TensorFlow can access it most generally.

**Comment by datnamer** [comment]
Yes, i think so. It woule be really nice to write normal python code to have full interop with edward models.

There  is even a issue there for integration with numba, which can JIT compile the code to around c speeds..though saod integration needs a champion right now.

**Comment by bhargavvader** [comment]
Would like to add here that a full python port of Dynamic Topic Models exists in gensim. :)
Here is the link to the notebook tutorial, in case anyone is interested: [DTM tutorial](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/ldaseqmodel.ipynb).

**Comment by datnamer** [comment]
Python models are gone right? I'm interested in using a generative model in python, which won't provide gradients, but I want to optimize the parameters.

**Comment by dustinvtran** [comment]
they're deprecated. can you describe your model in more detail? you can define non-differentiable models using the native edward language if that's the concern.

**Comment by datnamer** [comment]
Its an agent based model.
