### ISSUE TITLE
typo in getting started?

### ISSUE THREAD

**Issue by chrisranderson** [blei-lab/edward#159]
From http://edwardlib.org/getting-started/ :

> Here is a model of coin flips using a Beta-Bernoulli distribution in NumPy/Scipy.

The page linked to is a "Beta-binomial" distribution.

**Comment by dustinvtran** [comment]
Good point! This can be confusing because we use a Beta-Bernoulli model. It is a special case of a Beta-Binomial model with one trial (just as a Binomial generalizes a Bernoulli). I'm not sure of the best way to explain this without adding more words though.

**Comment by chrisranderson** [comment]
Footnote?
