### ISSUE TITLE
inconsistent stop_gradient usage

### ISSUE THREAD

**Issue by akucukelbir** [blei-lab/edward#172]
we sometimes use `edward.util.stop_gradient` and sometimes use `tf.stop_gradient`.

for example in https://github.com/blei-lab/edward/blob/master/edward/inferences.py#L354 and other methods in `inferences.py`

**Comment by dustinvtran** [comment]
The consistency is that we use `tf.stop_gradient(x)` if `x` is a `tf.Tensor`, as per its vanilla usage; and we use `edward.util.stop_gradient(x)` if `x` is any other data structure (`list`, `dict`, objects which may or may not be a `tf.Tensor`).

**Comment by akucukelbir** [comment]
is the overhead too much to just use `edward.util`? for simplicity/readability/debugging?

**Comment by dustinvtran** [comment]
For mantainability reasons, I personally like sticking as much to default TensorFlow functions as I can. This nuance with using `edward.util.stop_gradient` vs `tf.stop_gradient` is not obvious when reading through the lines of code in inference though. So it's less readable for a subset of our audience (algorithmic researchers) but at the benefit of maintainability. 

In this case maybe the better choice is to always use `edward.util.stop_gradient`?

**Comment by akucukelbir** [comment]
i think using `edward.util.stop_gradient` everywhere makes sense in this situation. just my two cents though.

**Comment by dustinvtran** [comment]
Yep I agree. Hopefully someone can write a quick patch and submit the pull request. :)
