### ISSUE TITLE
Simple tests of full models

### ISSUE THREAD

**Issue by altosaar** [blei-lab/edward#174]
Unit tests should include things like linear/logistic regression or a simple deep latent gaussian model, either on MNIST or synthetic data.

This will help make sure any changes to the API recover the same ELBO across a suite of test models. 

If MNIST is too computationally intense, we can create synthetic data.

**Comment by dustinvtran** [comment]
Thanks for the reference! Yep, sounds useful. @mariru is working on that in https://github.com/blei-lab/edward/issues/125

**Comment by dustinvtran** [comment]
Fixed in #487
