### ISSUE TITLE
edwardlib url paths for tutorials

### ISSUE THREAD

**Issue by dustinvtran** [blei-lab/edward#178]
The names at the moment, e.g., `edwardlib.org/tut_KLpq_score` are difficult to read. Ideally, it would look like `edwardlib.org/tutorials/KLpq-score`, `edwardlib.org/tutorials/variational-inference`, `edwardlib.org/supervised-learning-regression`, etc.

**Comment by akucukelbir** [comment]
yes. also we should be consistent with `_` and `-`. (my bad.)
