### ISSUE TITLE
Gaussian mixture example

### ISSUE THREAD

**Issue by DarkSensei** [blei-lab/edward#185]
I've been trying to experiment a bit with the GMM example, drawing a scatter plot etc., but I can't get the model to actually work (code: https://gist.github.com/DarkSensei/b7d31ff7d3d38633df11ab6316865b9a) . I did some poking around, and the only way I could get the model to learn, is by setting the variances to be unit, otherwise they just explode into large numbers. I'd appreciate if someone could lend a hand with this.

**Comment by fmpr** [comment]
Hi,

First of all, congratulations on developing edward!
I was looking into some of the examples and I think the mixture of gaussians example is not correct. 
Consider a simple mixture of 2 gaussians with joint probability:
`\prod_{n=1}^N ( \lambda \N(x|\mu_1,\sigma_1) + (1-\lambda) \N(x|\mu_2,\sigma_2) )`
Taking the log of this gives:
`\sum_{n=1}^N \log ( \lambda \N(x|\mu_1,\sigma_1) + (1-\lambda) \N(x|\mu_2,\sigma_2) )`
However, the example code is computing (correct me if I'm wrong...):
`\sum_{n=1}^N ( \log \lambda + \log \N(x|\mu_1,\sigma_1) + \log (1-\lambda) + \log \N(x|\mu_2,\sigma_2) )`
which is not the same thing. It completely bypasses the log-sum-exp issue, which makes things easier to compute, but then the results are wrong.

I did some tests with a very simple artificial dataset consisting of a mixture of two bi-dimensional gaussians with centers on [-1,-1] and [1,1]:

`def build_toy_dataset(N):

	pi = np.array([0.4, 0.6])
	mus = [[1,1],[-1,-1]]
	stds = [[0.1,0.1],[0.1,0.1]]
	x = []
	colors = cm.rainbow(np.linspace(0, 1, 2))
	for n in xrange(N):
		k = np.argmax(np.random.multinomial(1, pi))
		x.append(np.random.multivariate_normal(mus[k],np.diag(stds[k])))
		plt.scatter(x[n][0], x[n][1], color=colors[k])
	plt.show()
	return {'x': np.array(x).astype(np.float32)}`

The means inferred by the example code are completely off:
`mean: 
[ 0.48774096 -2.39035225 -1.22405362  0.62153614]`

I changed the log lik in the example code (naively) to be:

		log_lik = []
		n_samples = get_dims(zs[0])[0]
		for s in range(n_samples):
			log_lik_z = 0.0

			for k in range(self.K):
				result = tf.exp(norm.logpdf(x, mus[s, (k*self.D):((k+1)*self.D)], sigmas[s, (k*self.D):((k+1)*self.D)]))
				result = tf.matmul(result, tf.transpose(pi))
				result = tf.reduce_sum(result, 0)
				log_lik_z += tf.log(result)

			log_lik += [log_lik_z]

This seems to give results closer to the true means:
`[-0.83513373 -1.56447959  0.8101908   0.46021864]`
However, they are still a bit off, and this is not a very numerically stable way of computing log-sum-exps. I'm new to TensorFlow... Probably this could be done in a much better way... Any tips would be appreciated.

**Comment by dustinvtran** [comment]
Thanks @fmpr for spotting that! I submitted a pull request to incorporate log sum exp in the joint density (see #205).
