### ISSUE TITLE
tf.name_scope()'s and tensorboard

### ISSUE THREAD

**Issue by dustinvtran** [blei-lab/edward#190]
We need to include these for [easy viewing of the graph](https://www.tensorflow.org/versions/master/how_tos/graph_viz/index.html) in Tensorboard. Also related to default diagnostics that can be visualized in Tensorboard, c.f., https://github.com/blei-lab/edward/issues/106.

**Comment by matthewdhoffman** [comment]
It seems like the new random variable classes would benefit from this—the old `DistributionTensor`s encapsulated the parameters and samples in the same namespace.

**Comment by dustinvtran** [comment]
One question is when to provide matplotlib/seaborn features for visualization, versus when to provide TensorBoard features for visualization.

+ My initial guess is that TensorBoard is useful for visualizing internals which users don't have explicit access to. This means #351 (visualizing a model's graph structure) and #353 (inference/convergence diagnostics).

+ On the other hand, matplotlib/seaborn is useful for visualizing things the users must call explicitly. This means #279 (visualizing high-dimensional distributions), #352 (visualizing fitted models), and #354 (criticizing fitted models).

(But it's a wash. The [TensorBoard embedding visualizer](https://www.tensorflow.org/get_started/embedding_viz) shows that it can also be an excellent platform for interactively visualizing fitted models.)

**Comment by closedLoop** [comment]
I am working on this now and have made good progress.   Will report back shortly with a pull request
