### ISSUE TITLE
Inference via ADVI

### ISSUE THREAD

**Issue by MannyKayy** [blei-lab/edward#193]
Hi, is there any plan to support [Automatic Differentiation Variational Inference](http://arxiv.org/abs/1603.00788)?

**Comment by dustinvtran** [comment]
Hi @MannyKayy, co-author of the paper here. Short answer is yes. 

Long answer is that it's not a high priority, and it should come within a month or two after the native modeling language is merged (which will take that month or two). The current difficulty is that internally, with the current modeling languages, we have no knowledge of the support of the latent variables. This means automated transformations are not possible. This "attribute" will be available in the native modeling language, and we'll be able to go past the current ADVI by leveraging other recent VI techniques such as [hierarchical variational models](https://arxiv.org/abs/1511.02386).

**Comment by MannyKayy** [comment]
Alright, thanks. I'll be looking forward to it.

**Comment by pedrofale** [comment]
Hi @dustinvtran, is Coordinate Ascent Variational Inference coming up anytime soon?

**Comment by dustinvtran** [comment]
Symbolic algebra is hard. Still in experimental stages.

**Comment by leachim** [comment]
I would also be interested in Coordinate Ascent Variational Inference. Could you point me to the experimental code? I might find some time to add to it.

**Comment by pswpswpsw** [comment]
Hi @dustinvtran , is currently ADVI (the one that uses gradient from the model) implemented in Edward as **Stochastic variational inference**? I saw the paper and it says yes. But in the API I saw **no**. This is from the API website: **[This class minimizes the objective by automatically selecting from a variety of black box inference techniques](http://edwardlib.org/api/ed/KLqp).**
