### ISSUE TITLE
Error in "First Edward Program"

### ISSUE THREAD

**Issue by nfoti** [blei-lab/edward#200]
The "Your First Edward Program" example from the webpage errors out on an `AttributeError` saying that the `BayesianNN` instance has no attributed `neural_network`.

**Comment by dustinvtran** [comment]
Hi Nick. Have you checked out the associated Python script (https://github.com/blei-lab/edward/blob/master/examples/getting_started_example.py)? We cut some things out of the code snippets to keep it easier to follow.

**Comment by nfoti** [comment]
I just totally missed the link to the code. Thanks.

**Comment by dustinvtran** [comment]
No problem!
