### ISSUE TITLE
hierarchical logistic regression example needs a hierarchical data set

### ISSUE THREAD

**Issue by dustinvtran** [blei-lab/edward#210]
per @akucukelbir's complaint, the current example is technically _bayesian_ logistic regression, not hierarchical logistic regression. (i hate this terminology)

**Comment by akucukelbir** [comment]
it was more of a remark than a complaint. :) regardless, do not take my comment as an endorsement of either. (my greatest issue is with the word "regression" in "logistic regression." but i gave up on that years ago.)

**Comment by dustinvtran** [comment]
renamed to bayesian logisitic regression in #528; for hierarchical, see linear mixed model and/or irt model examples.
