### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by simonkamronn** [blei-lab/edward#233]
In #225 you changed a lot of the examples from proper [PEP 8](https://www.python.org/dev/peps/pep-0008/#indentation) indentation to something else with 2 space indentations. Please consider reversing that.

**Comment by dustinvtran** [comment]
Yeah we switched to 2-space indentation following [TensorFlow's style](https://www.tensorflow.org/versions/master/how_tos/style_guide.html#python-style). It made it easier for various collaboration reasons, where sometimes we default to NumPy style, others PEP 8, and others TensorFlow. For most things we're transitioning more and more to adopting whatever TensorFlow adopts as the default style.

**Comment by simonkamronn** [comment]
Alright, I'll take it up with the TensorFlow team then.
