### ISSUE TITLE
MixtureGaussian prior on sigma

### ISSUE THREAD

**Issue by akuz** [blei-lab/edward#250]
InverseGamma distribution is a conjugate prior for the variance of a normal distribution, not standard deviation. However, in the example code for MixtureGaussian it is used as a prior for sigmas, not sigmas^2. I guess it doesn't matter too much, as the inference doesn't rely on the conjugacy (?). But it might be still useful to square the sigmas before evaluating the prior log likelihood in this code: log_prior += tf.reduce_sum(invgamma.logpdf(sigmas, self.a, self.b)).

**Comment by dustinvtran** [comment]
Good catch! Yeah the algorithm uses a form of non-conjugate inference. But your note will surely matter as we start implementing conjugate algorithms.

**Comment by akuz** [comment]
Чуваки прониклись моим комментарием на edward

**Comment by akuz** [comment]
Sorry didn't mean to send this :)

**Comment by dustinvtran** [comment]
Fixed in https://github.com/blei-lab/edward/pull/612.
