### ISSUE TITLE
streaming data

### ISSUE THREAD

**Issue by dustinvtran** [blei-lab/edward#26]
Implementation-wise, this is the setting where we can't store all of the data inside the `Data` class. What's the best way to couple this problem when streaming is integrated into the iterations of `inference.run()`?

**Comment by mariru** [comment]
I want to revive this issue. 
There are examples like the [mixture density network](https://github.com/blei-lab/edward/blob/master/examples/tf_mixture_density_network_demo.py) where data is a `tf.placeholder` in the model and then fed during inference using `feed_dict`.
Really what is missing is a general method to subsample data during inference for the `feed_dict` similar to the functionality of `mnist.train.next_batch()` in the tensorflow mnist tutorial.

**Comment by mariru** [comment]
@dustinvtran @dawenl 
A general solution could do something similar as this (the code snippet is part of an example I am currently working on).
As Dawen suggested in #25  I am using yield.

```
# DATA
data = {'x': x, y: l}
n_minibatch = 10

def splice(x,i,j,l):
    if j>=l:
        return np.hstack((x[i:],splice(x,0,j-l,l)))
    else:
        return x[i:j]
        
def batch_generator(x,n_minibatch=10):
    j = 0
    l = len(x)
    while True:
        i = j%l
        j = i+n_minibatch
        yield splice(x,i,j,l)
        
train_batches = batch_generator(np.loadtxt('../../dat/klijn/train_idx.txt').astype(int), n_minibatch)
test_batches = batch_generator(np.loadtxt('../../dat/klijn/test_idx.txt').astype(int), n_minibatch)

# INFERENCE
for i in range(n_iter):
    train_idx = train_batches.next()
    test_idx = test_batches.next()
    _, train_loss[i] = sess.run([inference.train, inference.loss],
                              feed_dict={x: features[train_idx,:], l: labels[train_idx,:]})
    test_loss[i] = sess.run(inference.loss,
                              feed_dict={x: features[train_idx,:], l: labels[train_idx,:]})
    print("Train Loss: {:0.3f}, Test Loss: {:0.3f}".format(train_loss[i],
                                                         test_loss[i]))
```

**Comment by dustinvtran** [comment]
For streaming from files, I recommend using TensorFlow's [file readers](https://www.tensorflow.org/versions/master/how_tos/reading_data/index.html#reading-from-files). Basically, they take a file as input and output a data tensor. The data values in the tensor will change at each session run (according to settings in the file reader). Edward's inference can operate on these data tensors as if they were just any other data. 

Feeding values into placeholders according to a generator also works. I think file readers are more scalable when we start to do distributed computing though. (Plus, it keeps Edward lightweight without having to write any infrastructure for data.)

There's sparse documentation on how to use Edward with file readers in the [data API](http://edwardlib.org/api/data). It would be great to have a real-world example.

**Comment by dawenl** [comment]
I haven't looked into TensorFlow's file readers, but wouldn't be surprised if they internally implement it as something similar to a generator. 

I think overall if the data is of regular type that is supported by the TensorFlow's file readers, then it is good to use it. On the other hand, for more complicated data format (more complicated than csv or images) or structure (e.g., trees), writing customized generator with `feed_dict` might be a better choice.
