### ISSUE TITLE
can't initialize MAP inference

### ISSUE THREAD

**Issue by mariru** [blei-lab/edward#266]
PointMass needs `prob()` function.
When I run 
```
inference = MAP(...)
inference.initialize()
``` 
I get error 
```
...
/home/maja/Installs/src/edward/edward/models/point_mass.py in prob(self, x, name)
    186       prob: tensor of dtype `dtype`, the prob values of `x`.
    187     """
--> 188     raise NotImplementedError()
    189 
    190   def entropy(self, name="entropy"):

NotImplementedError: 
```

**Comment by dustinvtran** [comment]
Resolved in person, which was an error as it tried to calculate the log-density of a point mass. This method is not implemented yet. But in general, the log-density of a point mass is not required for MAP. (Well, unless your prior is a point mass, e.g., you're doing MLE.)

We'll implement it eventually!
