### ISSUE TITLE
a VIBES-like modeling language

### ISSUE THREAD

**Issue by dustinvtran** [blei-lab/edward#27]
It'd be nice to have a language to specify directed acyclic graphs, so we can take advantage of Rao-Blackwellization/Markov blankets. Also it'd be nice to take advantage of the case when all full conditional distributions are an exponential family.

**Comment by jluttine** [comment]
Hey, great work with Edward! Do you have any insight how difficult it would be to add support for conjugate-exponential family models (or sub-graphs) so that exact gradients could be utilized (as in variational message passing)? Would it be possible or straightforward with the current machinery? I suppose it would require that the log-density functions are written as functions of the sufficient statistics instead of the variables directly and that seems like a very big change to the current code base. Anyway, I might be interested to take a look on this if I find the time but any pointers or comments would be helpful. I can also open another issue, if you consider this to be slightly off-topic. Cheers!

**Comment by dustinvtran** [comment]
Hi @jluttine: The main difficulty is in the modeling language. I'm not familiar with a language that would let us take advantage of that structure. However, once it exists it is straightforward with the current machinery in a similar way you mention. The exact details depend on how fully conditional densities are encoded in the language.

**Comment by dustinvtran** [comment]
> Hi Dustin,
> 
> I read you blog today. I was struck with your amazing works related to variational Bayesian Inference.
> 
> I am also into Bayesian research but more into its applications for automating stuff. I had implemented an algorithm for learning parameters for mixed Bayesian networks. But that was in Matlab. 
> 
> I want to do that in python, does any of your library support Bayesian parameter learning for mixed networks from data? Or is it possible to do that using variational approximation some how. 
> 
> Please help.
> 
> Thanks and regards
> Aakanksha

Hi Aakanksha,

The library supports inference for arbitrary joint distributions (that is, any model which can be written as a tractable joint density of data and latent variables). This includes Bayesian networks, although I haven’t found a good Bayesian network/graphical modeling language in Python, so that we can take advantage of the Markov blanket structure. Once there is a way to obtain the Markov blanket for any individual latent variable, then we can do very fast variational inference on graphical models.

For more information see https://github.com/blei-lab/edward/issues/27. If you have bandwidth to look into that direction, then it would be huge for the graphical modeling community. Hope that helps!

Dustin

**Comment by datnamer** [comment]
https://github.com/pgmpy/pgmpy Have you see this? "Python Library for Probabilistic Graphical Models"

**Comment by Aakanksha-B** [comment]
@datnamer Yeah i have seen it. Faced some issues related to -[ prior specification](https://github.com/pgmpy/pgmpy/issues/685) and [belief propagation](https://github.com/pgmpy/pgmpy/issues/684) which have not been resolved yet.

**Comment by dustinvtran** [comment]
(for my own bookkeeping)

Hakaru (https://github.com/hakaru-dev/hakaru) has incredible symbolic computation where given a normal-normal model, it will compile and return the normal model marginalizing over the latent variable. This is a pretty cool way to deal with conjugacy. Moreover, it is a first step to thinking about compile-time optimization beyond just deterministic things (e.g., collapsing reducible operations) to operations with randomness.

We should look into how they deal with conjugacy.

**Comment by suhailshergill** [comment]
@dustinvtran you might find some of the following research related to hakaru useful:
- [Hakaru system description](http://homes.soic.indiana.edu/ccshan/rational/system.pdf)
  - [symbolic bayesian inference](http://www.cs.tufts.edu/~nr/pubs/disintegrator.pdf)
  - [simplifying using computer algebra](ftp://ftp.cs.indiana.edu/pub/techreports/TR719.pdf)
- [improvements on the original Hakaru](http://okmij.org/ftp/kakuritu/Hakaru10/PPL.pdf)

**Comment by dustinvtran** [comment]
Nice. Thanks for the references @suhailshergill. They are indeed very useful!

**Comment by suhailshergill** [comment]
np :)

**Comment by suhailshergill** [comment]
btw, @dustinvtran if/when you're in toronto give me a heads up. we would love to have you present in our probabilistic programming meetup here

**Comment by suhailshergill** [comment]
@dustinvtran PS github doesn't show `ftp` links, but i've edited my comment for the computer algebra paper

**Comment by dustinvtran** [comment]
Yeah, will definitely give you a heads-up! Also letting others in the group know.

**Comment by rokgerzelj** [comment]
Hey, any updates on this?

**Comment by dustinvtran** [comment]
You can see preliminary work on the branch [`feature/metagraph`](https://github.com/blei-lab/edward/tree/feature/metagraph). The pull request #192 makes progress from Edward's current API to support various things in the language.

There is a enormous number of challenges in the language design, which I've been furrying my brows to solve these past two months. Here are some concepts floating around to get a sense of what I'm working with:

1. Leveraging TensorFlow for math operations
2. Stochastic tensors and stochastic control flow
3. Operations on random variables vs operations on samples
3. Delayed construction of computational graphs
4. Separation of model and inference
5. Local vs global, i.e., what features go into a model "container" vs the individual random variables

Things will be more concrete as we finalize our ideas around the language implementation.
