### ISSUE TITLE
how deep is pymc3 link?

### ISSUE THREAD

**Issue by cmorgan** [blei-lab/edward#277]
Hi,
Thanks for Edward! I'm building up my Bayesian knowledge and it looks like a good resource.
For someone on the outside looking in could you explain how Edward fits in with pymc3. I see that there is a dependency on pymc3 as an extra.

Do you have any more examples of using Edward and pymc3 together?

Thanks!

**Comment by dustinvtran** [comment]
from an e-mail response:
>one way pymc3 and edward can join forces is to use pymc3’s modeling language alongside edward’s inference algorithms.
>we have a toy example of that here:
>
>https://github.com/blei-lab/edward/blob/master/examples/pymc3_beta_bernoulli.py
>
>there are a number of cool things we can also do. for example, leveraging pymc3’s built-in visualizations for understanding inferred posterior outputs. (edward currently lacks on the visualization side.)

**Comment by dustinvtran** [comment]
model wrappers, including `PyMC3Model`, are now deprecated (#344). 

with that said, i think it's still useful to incorporate visualizations from PyMC3—either indirectly by rebuilding some of their functionality within TensorFlow, or (if they operate on NumyPy arrays) to directly use them in our example scripts.

**Comment by twiecki** [comment]
None of the plotting or backend code uses theano.

**Comment by dustinvtran** [comment]
Support for external languages has been dropped in https://github.com/blei-lab/edward/releases/tag/1.2.3.
