### ISSUE TITLE
``build_loss_and_gradients`` functionality introduces subtle bug when using inheritance

### ISSUE THREAD

**Issue by bayerj** [blei-lab/edward#305]
The mean to implement special gradients that I proposed in #247 and which has been implemented by @dustinvtran has introduced quite a subtle bug. It is especially dangerous as it does not lead to a crash, but instead works apparently fine–but it actually uses the loss of a subclass. 

I am sorry for not seeing the danger of that pattern beforehand.

Consider the following hierarchy of inference classes, where the superclass has special gradients while the subclass wants to use standard gradients. If I am not mistaken, this bug is currently live in the IWAE example.

```
class FancyInference(VariationalInference):
  # relies on special gradients
  def build_loss_and_gradients(self, ...):
    ...

class FancierInference(FancyInference):
  # wants to use standard behaviour
  def build_loss(self, ...)
    ...
```

Here, the current funtionality will fall back on the loss from `FancyInference` when using `FancierInference`, since `build_loss_and_gradients` is inherited.

The only "hack" to deal with as of now is to overwrite `build_loss_and_gradients` in `FancierInference` and fall back to autodiff in there manually. This is obviously not user friendly.

The only elegant way out I see currently is to make `build_loss_and_gradient` the standard; the return value is `loss, gradient`. If the user wants to fall back on autodiff, she can return `loss, None` or so. 

If that is done, one could even go back to name it `build_loss`. Possibly, the caller can then even inspect the result's length, and depending on it either treat it as a loss only (if `len(result) == 1`) or loss and gradient (if `len(result) == 2`). I am undecided if that is too much magic.

But maybe someone else has a better idea.

**Comment by dustinvtran** [comment]
>The only elegant way out I see currently is to make build_loss_and_gradient the standard; the return value is loss, gradient. If the user wants to fall back on autodiff, she can return loss, None or so.

I think that proposal makes sense. In general, having two methods which aim to complete the same task can be confusing (and which as you state is a problem during inheritance).

**Comment by dustinvtran** [comment]
This is fixed a while back; all `VariationalInference` classes now use `build_loss_and_gradients`.
