### ISSUE TITLE
pls help find bayesian_nn.py for tensorflow since I use windows computer

### ISSUE THREAD

**Issue by Sandy4321** [blei-lab/edward#317]
pls help find bayesian_nn.py for tensorflow since I use windows computer
you may know code for windows computer since tensorflow is only for linux

**Comment by dustinvtran** [comment]
unfortunately we can't help you there. unless tensorflow supports windows (i think it does in recent versions?), edward simply won't be able to work. it heavily relies on tensorflow for infrastructure.

**Comment by dustinvtran** [comment]
[TensorFlow now supports Windows.](https://github.com/tensorflow/tensorflow/releases/tag/0.12.0-rc0)
