### ISSUE TITLE
 clarify sentence in getting started example

### ISSUE THREAD

**Issue by dustinvtran** [blei-lab/edward#319]
from an e-mail:
> article says: "The model has learned the cosine relationship between x and y."
> 
> but from the figure, it is clearly the case that the posterior draws are not from a cosine function, rather, they are from something like a gaussian function.
> the model uncertainty below -3 and above +3 should be way bigger than it is.
> so, i think the model overfit the data.

the sentence could be clarified to say it learned the relationship within the range. or, more matter of factly, it fit the data.

**Comment by naesseth** [comment]
Another option is to include at least one period of data and try to learn the cosine relationship. But perhaps that makes the example more difficult than necessary for what you are trying to show?

**Comment by dustinvtran** [comment]
unless the model includes periodic behavior a priori, most likely the bayesian neural net would technically still not capture the cosine relationship outside the domain.

**Comment by naesseth** [comment]
Yep, that was what I meant by making the example more difficult than necessary. I.e. having to rework the model to capture the cosine behavior.
