### ISSUE TITLE
Maybe mention conda install

### ISSUE THREAD

**Issue by maedoc** [blei-lab/edward#321]
The docs mention that pip installing is a pain and then point to TF docs, but I tried via conda and conda forge, which ships 11.0rc0 and it's a little easier, just 

```
conda config --add channels conda-forge
conda create -n tfed numpy scipy six tensorflow
source activate tfed
pip install edward
```

**Comment by dustinvtran** [comment]
good idea! i have zero knowledge about conda.  can you explain what those lines do? is there a standard also for homebrew?

**Comment by maedoc** [comment]
Sorry I tend to assume anyone doing data science in Python uses `conda`, [a package manager which handles big binary Python extensions really well across the big 3 platforms](http://conda.pydata.org/docs/). In deploying anything Python as an application, I use it.

I also preface that these packages are *not* built with GPU support, so this is just a quick manner of starting. 

Once Anaconda or [Miniconda](http://conda.pydata.org/miniconda.html) is installed, you can add the [conda forge](https://conda-forge.github.io/) channel (just a source of packages)
```bash
conda config --add channels conda-forge
```
then create a conda environment (like virtual environment, but managed centrally by `conda`)
```bash
name=tfed
pkgs="python=3.5 numpy scipy six tensorflow=0.11.0rc0"
conda create -n $name $pkgs
```
To use it, 
```bash
source activate tfed
```
and then install libs via `pip` as necessary
```bash
pip install edward ipython
```

#### homebrew

I've used a OSX over last few months, and I know you can
```bash
brew install python2 python3
```
etc, but any binary packages not provided by `brew` need to be built from source, while `conda` ships built & optimized (e.g. w/ MKL) packages for OSX.

**Comment by dustinvtran** [comment]
Very cool. Where do you suggest this write-up go? After the "TensorFlow is not on PyPI yet. We recommend using pip to install the latest TensorFlow binaries. Please follow the instructions from Google." in the troubleshooting page?

**Comment by maedoc** [comment]
Yes, with the disclaimer that the conda forge packages are CPU only.

I expect it's also possible to upgrade from the conda CPU only version to Google's GPU enabled version without problems, though I haven't tried this.

**Comment by dustinvtran** [comment]
all sounds good. i'd like you to get contributor credit. could you submit a PR with the proposed changes?

**Comment by maedoc** [comment]
@dustinvtran #328, I left out details because conda users usually know what those commands would do

**Comment by maedoc** [comment]
closing & mv discussion to PR I suppose
