### ISSUE TITLE
AttributeError with the Multinomial in ed.models

### ISSUE THREAD

**Issue by menxia** [blei-lab/edward#335]
#z = Multinomial( n = tf.ones(1), p = tf.constant([0.5, 0.3, 0.2]))
AttributeError: 'Multinomial' object has no attribute '_sample_n'

**Comment by dustinvtran** [comment]
thanks for the report. Edward builds off distributions available in the [TensorFlow distributions API](https://www.tensorflow.org/versions/master/api_docs/python/contrib.distributions.html). sampling is not currently implemented for Multinomial unfortunately.

if you're using one trial and can work with manual conversion from categorical value to one-hot, i recommend using `Categorical`.
