### ISSUE TITLE
remove support for model wrappers?

### ISSUE THREAD

**Issue by dustinvtran** [blei-lab/edward#341]
model wrappers have specific use cases, primarily for convenience. 

however, they expose too little model structure for efficient inference in many algorithms (if they're even supported in the algorithm); they cannot be efficiently distributed and/or leveraged with GPUs; and they make the code base somewhat bloated and difficult to navigate. i propose we remove them.

**Comment by dawenl** [comment]
This might have been resolved, but what if the model has somewhat unconventional likelihood which is not implemented as a `RandomVaribles`?

**Comment by dustinvtran** [comment]
there's no documentation on it presently, but you can implement your own random variable, inheriting from `RandomVariable`. the only requirement is to sample from it.

**Comment by dawenl** [comment]
If it's on the likelihood, why do we need to be able to sample from it? Is this for model criticism?

**Comment by dustinvtran** [comment]
each random variable is associated to a tensor in the graph which corresponds to its sample. that's right, we technically don't need to sample from it if we overwrite its tensor using the `value` argument every time. (which is how we currently work with Poisson likelihoods such as in [`latent_space_model.py`](https://github.com/blei-lab/edward/blob/master/examples/latent_space_model.py#L39))

**Comment by bhargavvader** [comment]
@dustinvtran , how exactly would you go about using the native language instead?
For example, in the `examples/tf_gp_classification.py` script, it uses a Gaussian Process model object. How would this be replaced?

**Comment by dustinvtran** [comment]
hi @bhargavvader, there's an equivalent `gp_classification.py` file that rewrites in the edward language. that could be a good reference. how to use the native language is in the docs: http://edwardlib.org/api/model

**Comment by bhargavvader** [comment]
Thanks for the links/reply. :)

**Comment by datnamer** [comment]
Is there a slimmer and more maintainable way to do this? Or perhaps an abstract class I can maintain a concrete subclass of in a different package? I'm interested in providing generative  nodes in numba etc for ABC and would be a shame to lock in to only tensorflow when python has a huge ecosystem of other modeling tools.

**Comment by dustinvtran** [comment]
i think the concept of supporting model wrappers is nice. in practice, however, there are 3 primary difficulties:

1. flexibility of inference, where it's not always obvious how to tweak the model class to support algorithms when they require more (or less) than the model's joint density;
2. computational speed of inference, where the bottleneck in computation is the model's log-likelihood, which thus should be written in TensorFlow anyways; and
3. hard-to-read code, where all our algorithms in the code base do some nasty if-else statements to handle model wrappers separately.

**Comment by datnamer** [comment]
Understood, thanks.

**Comment by dustinvtran** [comment]
Removed in [Edward v1.2.3](https://github.com/blei-lab/edward/releases/tag/1.2.3).
