### ISSUE TITLE
(MAP) Inference object is supposed to be stateless, but apparently not

### ISSUE THREAD

**Issue by dawenl** [blei-lab/edward#347]
To reproduce the problem:
```
import edward as ed
import numpy as np
import tensorflow as tf

from edward.models import Normal, PointMass

ed.set_seed(42)

# DATA
x_data = np.array([5.0] * 50, dtype=np.float32)

# MODEL: Normal-Normal with known variance
mu = Normal(mu=0.0, sigma=1.0)
x = Normal(mu=tf.ones(50) * mu, sigma=1.0)

qmu1 = PointMass(params=tf.Variable(0.0))
qmu2 = PointMass(params=tf.Variable(0.0))

# INFERENCE
data = {x: x_data}
inference = ed.MAP({mu: qmu1}, data)
inference.run()
inference = ed.MAP({mu: qmu2}, data)
inference.run()
```

The two runs will produce drastically different results. 

Only verified `ed.MAP`, maybe also affects other `Inference` subclasses.

**Comment by dustinvtran** [comment]
after discussion with @dawenl, this is a result of the `copy` scopes during inference being the same for every instantiated inference object. the scope needs to be different for each inference; otherwise it will reuse computation from a previous inference, which is incorrect.

**Comment by dawenl** [comment]
So to be more concrete to this above example, the loss for the second run is
`log p(x| mu=qmu1) + log p(mu; qmu2)`.
