### ISSUE TITLE
Inferring a histogram with Edward: indexing a multivariate random variable and the HalfNormal RV

### ISSUE THREAD

**Issue by niekbouman** [blei-lab/edward#349]
dear developers,

First of all thank you for your great work on stan & edward!

I have some questions about a particular histogram modeling problem, using Bayesian inference with dirichlet+hierarhical model prior and multinomial likelihood.

More precisely, I'd like to model a histogram with _N_ bins by means of a mixture of several (say, three, for the sake of example) components _X_i_, where the latter are length-_N_ vectors. The mixture coefficients, α_1,α_2,α_3 are Dirichlet distributed (they sum to 1).

I model the likelihood as multinomial, hence, observations _Y_, a length-_N_ vector with the bin counts, are 
_Y_ ∼ Multinomial(p = **α** ∙ **X** )  

One component, X_1, has a gamma  shape, with parameters k and theta

The second component, X_2, has a unit spike at position 1,

The third component, X_3, has  spikes at multiples of ten, and is normalized such that sum(X_3) = 1

I succeeded to build this model in PyMC3, but I run into issues with MCMC for any sampler other than Slice sampling, and ADVI fails as well (ELBO is always nan). Also, inference becomes very slow when increasing the number of bins to, say, a million bins.  (I show the PyMC3 model below, with only 31 bins)

How to code this in Edward? 
I tried making a Dirichlet, but I cannot using indexing.

```python
weights = ed.models.Dirichlet(alpha = tf.ones(num_terms))
...
... weights[0] ...
```
`TypeError: 'Dirichlet' object does not support indexing` 

And, how should I reproduce PyMC3's HalfNormal?
Just like:
```
k = tf.abs( ed.models.Normal(mu=tf.zeros(1), sigma=tf.ones(1))) 
```
?

best,
Niek

# PyMC3 model

```python
# data looks as follows
counts = [0, 8531, 487, 400, 284, 498, 236, 225, 255, 230, 1241, 165, 166, 130, 169, 235, 150, 155, 156, 147, 757, 140, 147, 132, 135, 417, 140, 163, 116, 108, 619]
%matplotlib inline
import matplotlib.pyplot as plt
plt.bar(range(len(counts)),counts)
```

```python
import pymc3 as pm
import numpy as np
import theano.tensor as T

number_of_bins = len(counts)

def create_multiples_vec(multiple,decay,weight,length):
    # create a comb with decaying spikes
    # like
    # w * [ 0 ... 0 (d^0) 0 ... 0 (d^1) 0 ... 0 (d^2) 0 ... etc. ]
    #                  <---- m ---->
    # where d = decay \in [0,1], w = weight, m = multiple
    ran = np.arange(length) 
    indicator = np.zeros_like(ran) 
    indicator[(ran % multiple==0) & (ran>0)] = 1 
    exponents = np.zeros_like(ran) 
    exponents[indicator==1] = np.arange(sum(indicator)) 
    term = indicator * (decay ** exponents) 
    return weight * term / T.sum(term) 

# specify the model 
with pm.Model() as my_hist_model: 

    num_terms = 3   
    weights = pm.Dirichlet('weights',a=np.ones(num_terms), testval = np.ones(num_terms) / num_terms ) 

    # Gamma component
    
    # -- its parameters
    k = pm.HalfNormal('k',sd=1,testval = 1) 
    theta = pm.HalfNormal('theta',sd=1,testval = 1) 

    # -- zero mass at position zero
    mask = np.ones(number_of_bins) 
    mask[0] = 0
    
    # -- unnormalized gamma (we normalize below)
    gamm = mask * (ran_inc ** (k-1) * T.exp(-ran_inc / theta)) 
    
    # Spike component (Kronecker delta at position one)
    spike = np.zeros(number_of_bins) 
    spike[1] = 1 

    # Beta decay of Comb component 
    decay = pm.Beta('decays',alpha=1,beta=1, shape=1) 

    
    histmodel = weights[0] * spike + \
                weights[1] * gamm / T.sum(gamm) + \
                create_multiples_vec(10,decay,weights[2],number_of_bins) 
    
    likelihood = pm.Multinomial('likelihood', n=sum(counts), p=histmodel, observed=counts)
```

**Comment by dustinvtran** [comment]
hey @niekbouman, you can use `tf.gather` for indexing. for the half normal distribution, we don't have it currently implemented unfortunately. however, you can define it with [`TransformedDistribution`](https://www.tensorflow.org/versions/r0.11/api_docs/python/contrib.distributions.html#TransformedDistribution). alternatively, you can do what you did by explicitly placing `tf.abs()` over a `Normal` random variable. (note however that it's a different model.)

**Comment by niekbouman** [comment]
Dear Dustin,
Thank you very much, `tf.gather` indeed works!

I now try to use the `Multinomial` class (`edward.models.Multinomial`), where I seem to run into the same problem as @luhaowang (issue #320 ): there seems to be some data type issue here, when I pass `n` as an integer, and `p` as a vector of `float32`, I get 

> ValueError: Tensor conversion requested dtype int64 for Tensor with dtype float32: 'Tensor("Multinomial_20/p/Identity:0", shape=(5,), dtype=float32)'

If I, instead, cast `n` to a float32, similar to how Multinomial is used in the examples given in 
[Tensorflow api docs](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard3/tf.contrib.distributions.Multinomial.md), then I get another error:
> TypeError: if `n` is not an integer type.
...
> AttributeError: 'Multinomial' object has no attribute '_sample_n'

Any idea how solve that problem?

best regards,
Niek

Code
```python
import tensorflow as tf
import edward as ed
import numpy as np

counts = [2, 4, 5, 7, 8]
number_of_bins = len(counts)

num_model_terms = 2   
weights = ed.models.Dirichlet(alpha = tf.ones(num_model_terms))

k = tf.abs( ed.models.Normal(mu=tf.zeros(1), sigma=tf.ones(1))) 
theta = tf.abs( ed.models.Normal(mu=tf.zeros(1), sigma=tf.ones(1))) 

ran_inc = tf.cast(tf.range(number_of_bins),tf.float32) + 1
gamm = (ran_inc ** (k-1) * tf.exp(-ran_inc / theta)) 
gamma = gamm / tf.reduce_sum(gamm)

kronecker = tf.SparseTensor(indices = [[1]],values=[1.0], shape=[number_of_bins])

distmodel = tf.gather(weights,1) * gamma + tf.sparse_tensor_to_dense(tf.gather(weights,0) * kronecker)

y = ed.models.Multinomial(n=np.sum(counts),p=distmodel)
```
