### ISSUE TITLE
Name Error in inference.py if theano is missing

### ISSUE THREAD

**Issue by lfloeer** [blei-lab/edward#359]
Line 156 in `inference.py` can raise a `NameError` if theano is not installed on the system. An example of this is running the `bayesian_linear_regression.py` example: If theano is present, the data assigment by variables works (line 44 in the example). If theano is not present, you have to reference the placeholders as strings, i.e. `data = {'X': X_train, 'y': y_train}`, to get the example to work.

**Comment by dustinvtran** [comment]
thanks! that makes sense. maybe the easiest solution is to wrap those lines in a try/except?
