### ISSUE TITLE
Issue with Multinomial ?

### ISSUE THREAD

**Issue by niekbouman** [blei-lab/edward#369]
Dear Edward developers,

I try to use the `Multinomial` class (`edward.models.Multinomial`), where I seem to run into the same problem as @luhaowang (issue #320 ): there seems to be some data type issue here, when I pass `n` as an integer, and `p` as a vector of `float32`, I get 

> ValueError: Tensor conversion requested dtype int64 for Tensor with dtype float32: 'Tensor("Multinomial_20/p/Identity:0", shape=(5,), dtype=float32)'

If I, instead, cast `n` to a float32, similar to how Multinomial is used in the examples given in 
[Tensorflow api docs](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard3/tf.contrib.distributions.Multinomial.md), then I get another error:
> TypeError: if `n` is not an integer type.
...
> AttributeError: 'Multinomial' object has no attribute '_sample_n'

Any idea how solve that problem?

best regards,
Niek

Code
```python
import tensorflow as tf
import edward as ed
import numpy as np

counts = [2, 4, 5, 7, 8]
number_of_bins = len(counts)

num_model_terms = 2   
weights = ed.models.Dirichlet(alpha = tf.ones(num_model_terms))

k = tf.abs( ed.models.Normal(mu=tf.zeros(1), sigma=tf.ones(1))) 
theta = tf.abs( ed.models.Normal(mu=tf.zeros(1), sigma=tf.ones(1))) 

ran_inc = tf.cast(tf.range(number_of_bins),tf.float32) + 1
gamm = (ran_inc ** (k-1) * tf.exp(-ran_inc / theta)) 
gamma = gamm / tf.reduce_sum(gamm)

kronecker = tf.SparseTensor(indices = [[1]],values=[1.0], shape=[number_of_bins])

distmodel = tf.gather(weights,1) * gamma + tf.sparse_tensor_to_dense(tf.gather(weights,0) * kronecker)

y = ed.models.Multinomial(n=np.sum(counts),p=distmodel)
```

**Comment by shoyer** [comment]
tf.contrib.distributions needs sampling to be implemented for Multinomial (and also Binomial and Poisson, among others). For now, I've been able to make this work by defining a custom Distribution subclass and adding in a `_sample_n` method that calls a numpy.random method via `tf.py_func`.

It would be nice to either codify these fixes in Edward or better yet fix it upstream in TensorFlow. I can also potentially work on an fuller example.

**Comment by dustinvtran** [comment]
also agreed with @shoyer. perhaps we can add a simple interface which will allow users to easily write `tf.py_func`s to build their own random variables. this can be a good temporary solution to any distributions not implemented yet in tensorflow.

**Comment by dustinvtran** [comment]
re:above. i wrote an example for implementing sampling in Poisson here: https://github.com/blei-lab/edward/issues/396#issuecomment-272079988. it would be nice to have documentation explaining this process.

**Comment by dustinvtran** [comment]
we describe how to implement your own sampling in http://edwardlib.org/api/model-development. in 1.0.0 multinomial is implemented. it will be available to use in the next edward version coming in a few days.

**Comment by niekbouman** [comment]
Nice!

best,
Niek
