### ISSUE TITLE
Edward Import Error

### ISSUE THREAD

**Issue by diehl** [blei-lab/edward#370]
After pip installing Edward and trying to run the simple example on the website, I ran into this error that occurs when importing Edward. Any idea what might be happening here???

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-646b2c48080c> in <module>()
----> 1 import edward as ed

/Users/cpd/anaconda/envs/DataGuild/lib/python2.7/site-packages/edward/__init__.py in <module>()
      3 from __future__ import print_function
      4 
----> 5 from edward import criticisms
      6 from edward import inferences
      7 from edward import models

/Users/cpd/anaconda/envs/DataGuild/lib/python2.7/site-packages/edward/criticisms/__init__.py in <module>()
      3 from __future__ import print_function
      4 
----> 5 from edward.criticisms.evaluate import *
      6 from edward.criticisms.ppc import *

/Users/cpd/anaconda/envs/DataGuild/lib/python2.7/site-packages/edward/criticisms/evaluate.py in <module>()
      7 import tensorflow as tf
      8 
----> 9 from edward.models import RandomVariable
     10 from edward.util import logit, get_session
     11 

/Users/cpd/anaconda/envs/DataGuild/lib/python2.7/site-packages/edward/models/__init__.py in <module>()
      5 from edward.models.models import *
      6 from edward.models.random_variable import *
----> 7 from edward.models.random_variables import *

/Users/cpd/anaconda/envs/DataGuild/lib/python2.7/site-packages/edward/models/random_variables.py in <module>()
     12 
     13 
---> 14 class Empirical(RandomVariable, distributions_Empirical):
     15   def __init__(self, *args, **kwargs):
     16     super(Empirical, self).__init__(*args, **kwargs)

/Users/cpd/anaconda/envs/DataGuild/lib/python2.7/site-packages/tensorflow/contrib/distributions/python/ops/distribution.pyc in __new__(mcs, classname, baseclasses, attrs)
    136     if not issubclass(base, Distribution):
    137       raise TypeError("First parent class declared for %s must be "
--> 138                       "Distribution, but saw '%s'" % (classname, base.__name__))
    139     for attr in _DISTRIBUTION_PUBLIC_METHOD_WRAPPERS:
    140       special_attr = "_%s" % attr

TypeError: First parent class declared for Empirical must be Distribution, but saw 'RandomVariable'

**Comment by rw** [comment]
What version of TF are you using? See https://github.com/blei-lab/edward/issues/363

**Comment by diehl** [comment]
tensorflow-0.12.0rc0 was installed on my machine when I pip installed edward. revert to tensorflow-0.11 in the mean time?

**Comment by diehl** [comment]
Just tried installing the latest development version and got the same issue...

**Comment by rw** [comment]
The solution I found (and wrote about in #363) is to install TF 0.11.

**Comment by diehl** [comment]
@rw sounds good - thanks. I'm actually trying to build that now from source...

**Comment by wookayin** [comment]
For the tracking of issue (dups): #315
