### ISSUE TITLE
Github integration request: Gitter chat

### ISSUE THREAD

**Issue by rw** [blei-lab/edward#375]
I've seen other projects have success with building community after adding Gitter chat. I think Edward would benefit. Is anyone else interested in this?

**Comment by dustinvtran** [comment]
i think this would be great, analogous to mailing lists. my only hesitance is timing, i.e., once there's an active enough user base for the chats to be productive.

**Comment by rw** [comment]
@dustinvtran I've found that it brings users out of the woodwork. Gitter definitely has a network effect, plus they seed the chat with users who've participated with the repository.

**Comment by dustinvtran** [comment]
that makes sense. i'll see if i can get it up this weekend. :)

**Comment by pwl** [comment]
How is it going with the gitter channel?  It would be nice to have some public space to ask beginner questions.

**Comment by dustinvtran** [comment]
apologies for the delay. done! (https://github.com/blei-lab/edward/pull/397)
