### ISSUE TITLE
KLqp is broken

### ISSUE THREAD

**Issue by gokceneraslan** [blei-lab/edward#376]
When I run `examples/beta_bernoulli.py`, posterior parameters do not change:

![image](https://cloud.githubusercontent.com/assets/1140359/21101525/e6e90d8c-c079-11e6-9c10-97c1073f3802.png)

After couple of iterations with `git bisect`, I ended up with 5bef0208a4b7171621b3703e5621e50c1a3e0c82, which seems to change the behaviour of KLqp. When I revert the commit, posterior parameters change:

![image](https://cloud.githubusercontent.com/assets/1140359/21101667/7ca1b950-c07a-11e6-9d2b-4470ce7ab28e.png)

**Comment by dustinvtran** [comment]
thanks for the bug report. it looks like #373 fixes this.
