### ISSUE TITLE
How to prevent tensorflow from allocating the totality of a GPU memory?

### ISSUE THREAD

**Issue by lijun900302** [blei-lab/edward#392]
I run exponential_family_embeddings   from https://github.com/mariru/exponential_family_embeddings.
Here is error:
Ran out of memory trying to allocate 93.13GiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:975] Resource exhausted: OOM when allocating tensor with shape[5000,100,50000]
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    sess.run([inference.train], feed_dict=d.feed(m.placeholders))

**Comment by dustinvtran** [comment]
this might be better asked on @mariru's github issues. in any case, pinging her in case she didn't catch this.

**Comment by lijun900302** [comment]
thank you! it is the problem of large Minibatch size.

**Comment by lijun900302** [comment]
@dustinvtran    thank you! It is the problem of large minibatch size.

**Comment by dustinvtran** [comment]
great!
