### ISSUE TITLE
Issues with the Poisson Random variable

### ISSUE THREAD

**Issue by yyaodong** [blei-lab/edward#396]
Hi,

I wanted to implement the compound Poisson models by SVI via Edward, following this paper:
http://jmlr.org/proceedings/papers/v48/basbug16.pdf

However, it has been mentioned in the tutorial section that:
"
Note Edward doesn’t currently support sampling for Poisson random variables. For now, we hard-code its associated tensor to be full of 0’s via the value argument. It is required only for instantiating the random variable and is not used in the experiment.
" 
I was wondering if there is any work-around to sample from Poisson in Edward?

Many thanks for the help.

**Comment by dustinvtran** [comment]
in general, you can write a custom random variable class that inherits `ed.models.RandomVariable` and `tf.contrib.distributions.Distribution`, and add your own own [`_sample_n()`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/distributions/python/ops/distribution.py#L557) method. `_sample_n()` takes an integer `n` as input and outputs a tensor of shape [`(n,) + batch_shape + event_shape`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/distributions/python/ops/distribution.py#L213). (to do the sampling, you can wrap the output of numpy or scipy as a tf.Tensor.)

following this, you can hack Poisson in Edward specifically by overwriting its `_sample_n()` method. for example:
```python
from edward.models import Poisson
def _sample_n(self, n, seed=None):
  return ...

Poisson._sample_n = _sample_n
```

**Comment by yyaodong** [comment]
Thanks for the reply.

I found that the newest version of Edward automatically generates random variable classes from classes in tf.contrib.distributions. And in tensorflow, Poisson distribution's sample_n methods is properly implemented, so I assume the current version of Edward should have no problem of making inference in the case where the latent variable follows a Poisson distribution, am I correct?

**Comment by dustinvtran** [comment]
great question. you have to wrap the scipy call in a tensorflow op using `tf.py_func`. this allows scipy to be called for each session run.

here's an example implementation
```python
from edward.models import Poisson
from scipy.stats import poisson

def _sample_n(self, n=1, seed=None):
  # define Python function which returns samples as a Numpy array
  np_sample = lambda lam, n: poisson.rvs(mu=lam, size=n, random_state=seed).astype(np.float32)
  # wrap python function as tensorflow op
  val = tf.py_func(np_sample, [self.lam, n], [tf.float32])[0]
  # set shape from unknown shape
  batch_event_shape = self.get_batch_shape().concatenate(self.get_event_shape())
  shape = tf.concat(0, [tf.expand_dims(n, 0),
                        tf.constant(batch_event_shape.as_list(), dtype=tf.int32)])
  val = tf.reshape(val, shape)
  return val

Poisson._sample_n = _sample_n

sess = ed.get_session()
x = Poisson(lam=tf.constant(1.0))
sess.run(x.value())
sess.run(x.value())
```
note you have to play with the `np_sample` function if you want scipy to broadcast correctly for non-scalar parameters.

**Comment by yyaodong** [comment]
Bravo solution through py_func. 

Thanks a lot!
