### ISSUE TITLE
format strings causes error in Python 3.4+

### ISSUE THREAD

**Issue by jkerfs** [blei-lab/edward#404]
When an object that does not implement `__format__` is passed to string format, format specifiers cannot be used in Python 3.4+.

For example (from examples/tf_mixture_density_network_demo.py):
```
print("Size of features in training data: {:s}".format(X_train.shape))
```
Raises an error in Python 3.4:
```
TypeError: non-empty format string passed to object.__format__
```

I think we can just replace `{:s}` with `{}`.

http://stackoverflow.com/questions/24170519/python-typeerror-non-empty-format-string-passed-to-object-format

https://bugs.python.org/issue7994

**Comment by dustinvtran** [comment]
good catch! i'd like you to get contributor credit. can you submit a PR that makes that simple change in all associated files?

**Comment by jkerfs** [comment]
Fixed in https://github.com/blei-lab/edward/pull/409
