### ISSUE TITLE
Gitter link on contributions page goes to strange site.

### ISSUE THREAD

**Issue by wmeddie** [blei-lab/edward#405]
On first glance, the contributions page looks fine but when I visit the currently deployed site in my browser the Gitter Channel link goes to "goinfotek dot com".  Perhaps one of the JS libraries is compromized?

**Comment by dustinvtran** [comment]
oops, looks like i linked to http://gitter.com/blei-lab/edward and not http://gitter.im/blei-lab/edward (use the latter). i'll fix this.

**Comment by dustinvtran** [comment]
fixed in 6520215db07176b59a9ce80c542cbeb0c83a9c9f
