### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by janvdvegt** [blei-lab/edward#420]
Hi, this package looks very exciting. I've been running Tensorflow for the past month on Windows now but I cannot get Edward to work on Windows. I'm using Anaconda with Python 3 and tensorflow 0.12.1 installed via a Wheel. What is in the way of getting it to work on Windows and is there something I could help with in that regard? When I do an import I get the following TypeError:

TypeError: First parent class declared for Empirical must be Distribution, but saw 'RandomVariable'

which happens in:

class Empirical(RandomVariable, distributions_Empirical) in random_variables.py

**Comment by stonebig** [comment]
setup.py specifies you must have Tenssorflow-0.11.something:
````
  install_requires=['tensorflow>=0.11.0rc0,!=0.12.0rc0,!=0.12.0rc1,!=0.12.0' +
                      ',!=0.12.1',
````

**Comment by janvdvegt** [comment]
So the issue is that edward doesn't work with TF 0.12 yet?

**Comment by dustinvtran** [comment]
that's right. also see #315
