### ISSUE TITLE
a small LDA example doesn't seem to work

### ISSUE THREAD

**Issue by ruzihao** [blei-lab/edward#423]
I was trying to implement the LDA example from the slides found [here](http://dustintran.com/talks/Tran_Edward.pdf)

The code is like:
```python
import numpy as np
import tensorflow as tf
from edward.models import Dirichlet, Multinomial, Categorical

D = 4
N = [11502, 213, 1523, 1351]
K = 10
V = 1000

theta = Dirichlet(alpha=tf.zeros([D, K]) + 0.1)
phi = Dirichlet(alpha=tf.zeros([K, V]) + 0.05)
z = [[0] * np.max(N)] * D
w = [[0] * np.max(N)] * D
for d in range(D):
    for n in range(N[d]):
        z[d][n] = Categorical(pi=theta[d, :])
        w[d][n] = Categorical(pi=phi[z[d][n], :])

```

I haven't actually implement the inference and criticism. I got this error message:

```
 (most recent call last):
  File "/Users/Hao/Documents/USEFUL/Datasets/PeoAna/PeoAnaCode/peoana/m5_edward/m1_examples/c4_latent_dirichlet_allocation.py", line 19, in <module>
    z[d][n] = Categorical(pi=theta[d, :])
TypeError: 'Dirichlet' object has no attribute '__getitem__'
```

How should I proceed with this error?

**Comment by dustinvtran** [comment]
indexing isn't currently implemented on tensors, so you would have to use `tf.gather`, e.g.,
```python
for d in range(D):
    for n in range(N[d]):
        z[d][n] = Categorical(p=tf.gather(theta, d))
        w[d][n] = Categorical(p=tf.gather(phi, z[d][n])
```
another note is that `p` as the argument isn't currently supported for Categorical's in tensorflow 0.11.0; so you would have to use the `logits` parameterization for now. for example,
```python
for d in range(D):
    for n in range(N[d]):
        z[d][n] = Categorical(logits=ed.logit(tf.gather(theta, d)))
        w[d][n] = Categorical(logits=ed.logit(tf.gather(phi, z[d][n])))
```
another note is about scalability of the model. we're writing lists of lists of scalars. we would need to vectorize these the generative process rather than nesting for loops over scalars to make inference fast.

**Comment by ruzihao** [comment]
Thanks a lot!

Are you suggesting using ed.tile() inside Categorical()?

**Comment by dustinvtran** [comment]
if necessary, i haven't thought too much about it. e.g., `z[d][n]` could probably vectorize over `n` by just forgetting the `tf.gather` altogether.

**Comment by ruzihao** [comment]
cool, appreciate your input :)

**Comment by gundeep59** [comment]
@ruzihao , @dustinvtran I am working on a different but a similar looking model. Can you possibly point me to examples/ tutorials that perform inference and criticism on such models?
Thanks in advance.

**Comment by dustinvtran** [comment]
Can you describe your model a bit more? LDA is a bit notorious in its difficulty to train without more model-specific algorithms. I think once we have conjugacy in (#588) we'll be able to write a large-scale LDA tutorial as well as train all sorts of mixed membership models.

**Comment by dustinvtran** [comment]
Closing as it's a user-implementation issue. See the Forum's thread for more details (https://discourse.edwardlib.org/t/confused-by-error-message-from-inference-run-for-lda-with-klqp/119); also see duplicates in #473, #476, #463.
