### ISSUE TITLE
sampling multiple variables at once (joint sampling)

### ISSUE THREAD

**Issue by willwhitney** [blei-lab/edward#427]
I assume there's a simple way to do this, but I haven't found it in the docs.

If I have a compositional model, e.g. 

```python
theta = Beta(a=1.0, b=1.0)
x = Bernoulli(p=tf.ones(50) * theta)
```

I can see a sample for `x` or `theta` by doing  `x.sample().eval()`.

However, I'm not clear on how to see a sample from the joint distribution `p(x, theta)`. I assume that if I do the following, I get a sample from each marginal, not one sample from the joint:

```python
theta_sample = theta.sample().eval()
x_sample = x.sample().eval()
# => samples from each marginal?
```

I could manually do the following to get a joint sample, but this seems pretty silly (for a nontrivial model):

```python
theta_sample = theta.sample().eval()
x_test = ed.copy(x, {theta: theta_sample})
x_test.sample().eval()
# => manually-constructed sample from the joint
```

Is there a simple way to, say, call `x.sample()`, then look at the values of the ancestor nodes which were used? Or is the sampling collapsed?

Alternatively, it would be nice to be able to do something like `theta_sample, x_sample = ed.sample(theta, x)`.

Sorry for the trivial question!

**Comment by dustinvtran** [comment]
recall that theta is a random variable, and it is associated to some value theta*. theta* represents a sample from p(theta); to get it, you call `theta.value()`. 

similarly, this means if you fetch x from the graph (`sess.run(x.value())`), it will follow the generative process: first, draw theta* ~ p(theta); second, draw x^* ~ p(x | theta*).

`sess.run(x.value())` represents a sample from the marginal in that you are drawing x ~ p(x) = int p(x, theta) dtheta. to get a sample from the joint, `sess.run([x.value(), theta.value()])` which will expose that draw of theta.

**Comment by willwhitney** [comment]
Ah, understood. Thanks so much!
