### ISSUE TITLE
doc mixture of gaussians

### ISSUE THREAD

**Issue by janekberger** [blei-lab/edward#436]
The [mixture of gaussians example](http://edwardlib.org/tutorials/unsupervised) mentions a Dirichlet prior over the mixture weights pi, but the [script linked](https://github.com/blei-lab/edward/blob/master/examples/mixture_gaussian_collapsed.py) doesn't involve that parameter. Also, the [unsupervised learning tutorial](http://edwardlib.org/tutorials/unsupervised) lists the variational distribution over pi in the inference step, but it's not part of the preceding model description.

**Comment by dustinvtran** [comment]
good catch. the unsupervised learning tutorial should take out `pi: qpi` in the dictionary to reflect the script.

**Comment by dustinvtran** [comment]
fixed in #438
