### ISSUE TITLE
Constrained parameters in Edward?

### ISSUE THREAD

**Issue by pourzanj** [blei-lab/edward#439]
In parameter estimation there are **non-holonomic constraints** e.g. a variance parameter for a Gaussian that must be positive, Bernoulli probability that must be between zero and one, or a strictly increasing set of parameters as used in ordered logistic regression. In Stan and PyMC3 these are handled by sampling on a transformed scale e.g. sampling a variance parameter on the log-scale and transforming the density evaluation appropriately. Does Edward's MCMC techniques do this automatically? It doesn't seem like there is a dichotomy between constrained and unconstrained parameters in Edward. How is it handled on the variational inference side? I'm guessing it's not an issue if your optimizer can have constraints as an input. 

My other question is about **holonomic constraints** which are equality constraints. The classical case is the Bingham–von Mises–Fisher distribution over spheres and distributions over orthonormal matrices, which are desired in PPCA. My lab mate and I are both interested in inferring these sorts of parameters for our problems.

[Byrne and Girolami introduced a technique for sampling HMC sampling on these distributions ](https://arxiv.org/pdf/1301.6064v2.pdf). It's very similar to standard HMC but the momentum updates have an extra step involving a projection that is parameter dependent, and the parameter updates are also somewhat different also in a way that depends on the type of constraint on the parameter you're trying to infer. This actually reduces to standard HMC as a special case. It would be nice to have this in Edward.

My question is what would be the best way to introduce this in to the existing software design of Edward? Again, it doesn't seem like Edward distinguishes between constrained and unconstrained RandomVariables. Would this be handled as a new distributions class? Would there be a new constraint class that new RandomVariables would inherit from in addition to RandomVariable and Distribution? One option would be to just implement the method by Byrne above as a child class of MonteCarlo, and have the user pass in a dictionary that specifies for each parameter the kind of constraint it satisfies. This could have some pretty ugly side effects if the user specifies a mismatched constraint though.

**Comment by dustinvtran** [comment]
Constraints can be placed either on latent variables (the random variables to be inferred) or parameters (model parameters, or parameters of a variational approximation):
1. We always work over constrained latent variables when performing inference. That is, we apply no transformations to unconstrain them. Unconstrained may be necessary for certain algorithms such as HMC. We're working on automated transformations on this regard in collaboration with TensorFlow devs: it requires implementing the support of each random variable.
2. For parameters, we always unconstrain them during optimization (variational inference). This is seen in the examples where we constrain the `tf.Variable` parameter of a Gaussian standard deviation.

re:holonomic constraints. It sounds like you're talking about how to work with latent variables that have equality constraints. This can be handled with automated transformations, similar to how one would apply them for HMC with inequality constraints. Stan does this for the von-Mises distribution and the Dirichlet.

Of course, a nice part of Edward is that there is room for many solutions. If you'd like a model-specific solution such as Byrne and Girolami (2013), I recommend implementing it as its own class—separate from the built-in HMC—for now. You can handle the parameter-dependent projections by simply looping over the latent variables and checking if they have circular support.

**Comment by pourzanj** [comment]
Thanks! That is helpful. 

> We always work over constrained latent variables when performing inference. That is, we apply no transformations to unconstrain them. Unconstrained may be necessary for certain algorithms such as HMC. We're working on automated transformations on this regard in collaboration with TensorFlow devs: it requires implementing the support of each random variable.

My main language is R, so I apologize for the simple question, but for now if I'd like to use MCMC and need to sample on the unconstrained space would the following work (using the normal_normal.py example)?

`mu = Normal(mu=0.0, sigma=1.0)`
`sigma_unconstrained = Normal(mu=0.0, sigma=1.0)`
`x = Normal(mu=tf.ones(50) * mu, sigma=tf.exp(sigma_unconstrained))`

Or perhaps it would be better to use `tf.contrib.distributions.TransformedDistribution`?

> It sounds like you're talking about how to work with latent variables that have equality constraints. This can be handled with automated transformations, similar to how one applies transformations for HMC with inequality constraints. Stan does this for the von-Mises distribution and the Dirichlet.

Yes, unfortunately there aren't known transforms for certain constraints. Byrne and Girolami is a solution to that.

> Of course, a nice part of Edward is that there is room for many solutions. If you prefer Byrne and Girolami (2013)'s approach, I recommend implementing it as its own class—separate from the built-in HMC—for now. You can handle the parameter-dependent projections by simply looping over the latent variables and checking if they have circular support.

Nice, I'll probably go ahead and try that. Edward's expandability is really useful in that respect! You mentioned supports have yet to be implemented though? Do you recommend I create my own RandomVariable classes?

**Comment by dustinvtran** [comment]
> My main language is R, so I apologize for the simple question, but for now if I'd like to use MCMC and need to sample on the unconstrained space would the following work (using the normal_normal.py example)? [..] Or perhaps it would be better to use tf.contrib.distributions.TransformedDistribution?

That example works. I could see one using `TransformedDistribution` to build a log-Normal distribution as the sigma prior; but that works again on a constrained space.

> Nice, I'll probably go ahead and try that. Edward's expandability is really useful in that respect! You mentioned supports have yet to be implemented though? Do you recommend I create my own RandomVariable classes?

Since there's no currently available random variables with circular support, you can just check if it is an instance of a specific class (the one which has the circular support), e.g., `if isinstance(x, CustomRandomVariable)`. yeah, it sounds like the first step would be to get a simple implementation of a distribution with holonomic constraints before then implementing Byrne and Girolami (2013) to solve it.

**Comment by pourzanj** [comment]
I got a chance too look more in to this. I don't think the code I posted would work, because once you re-parameterize, to get the new log joint density it's not enough to just evaluate the old one at the new parameter value. You also have to multiply by a Jacobian determinant term, and it doesn't look like the  _log_joint() function in hmc.py does that.

On the other hand, if one were to just create their own `TransformedDistribution` that should work because that Tensorflow class handles the multiplication by the Jacobian determinant whenever its log probability is called.

I wonder what the procedure is for adding a distribution to Tensorflow.

**Comment by dustinvtran** [comment]
The example works; it only depends on what you're trying to infer. (We use code like that all the time.) If you're inferring the posterior of `sigma_unconstrained`, it is again on the unconstrained space and works fine. If you're trying to infer the posterior of `sigma`, i.e., with the constraint, then you need to use `TransformedDistribution`.

You can code up your own random variables in Edward. See http://edwardlib.org/api/model-development
