### ISSUE TITLE
How were the Visualizations created?

### ISSUE THREAD

**Issue by QuantScientist** [blei-lab/edward#442]
Hi, 
Here, http://edwardlib.org/api/model-compositionality, the models are visualized. Was this created by hand or automatically using Python? 

Thanks,

**Comment by dustinvtran** [comment]
these were created by hand with tikz. you can get the source latex from the white paper's latex source if you'd like.

**Comment by QuantScientist** [comment]
Thanks dustin.

**Comment by QuantScientist** [comment]
Can you please share the Latex source code for the aforementioned document? I thought you were referring to:
https://github.com/blei-lab/edward/blob/master/docs/tex/api/model-compositionality.tex

Thanks.

**Comment by dustinvtran** [comment]
you can download it here, https://arxiv.org/format/1610.09787.
