### ISSUE TITLE
Inference on deterministic functions of RandomVariables

### ISSUE THREAD

**Issue by redst4r** [blei-lab/edward#444]
Hi,

I recently encountered the following problem: How do I perform inference with edward if my `data` is not directly a RandomVariable of the model, but rather some deterministic function of (multiple) RVs. 
For example, consider that we observe the sum of two Gaussians (lets ignore the fact that this could be calculated analytically), one with unknown mean (which we want to infer) and the other just 0-mean (e.g. measurement noise)

```python
mu = Normal(mu=0.0, sigma=1.0, name='mu')  # some prior over the mean

z = Normal(mu=tf.ones(N)*mu, sigma=1.0, name='z')
noise = Normal(tf.ones(N)*0,    sigma=2.0, name='noise')
x = tf.add(z,noise)
```

How would I do inference on `mu` here, given `N` samples of `x`?
Hitting it with the MCMC inference engine and just specifying `data={x: observed}` doesn't work (since `x` is not a RV it's ignored, see [here](https://github.com/blei-lab/edward/blob/master/edward/inferences/metropolis_hastings.py#L119)). 

Another idea was to wrap it with a 
```python
x = PointMass(tf.add(z,noise))
```
but  inference complains that there's no `_prob` defined on `PointMass`. 
I could probably provide this, just multiplying the densities of the parent nodes.
However, I'm not sure if this little hack would break anything deep inside edward and result in undesired effects that I'll never be able to find :)

Or is there already a strategy to deal with these deterministic transformations of RandomVariables within edward?

**Comment by dustinvtran** [comment]
when you model data as a deterministic function of random variables, there's no guarantee that the induced distribution admits an easy/tractable density. in other words, it typically has an intractable likelihood. this falls in the realm of simulator-based models, also known as implicit probabilistic models. inference on such models requires a likelihood-free approach, and current stuff such as our out of the box MCMC engines can't be applied.

that's a great question. we're currently researching methods for such models, combining stuff from GANs and ABC. i find such models really fascinating because gets at the notion of where randomness is even needed in models. none of our current work is available or finalized yet for edward.

**Comment by shoyer** [comment]
Even more problematic would be if you depended on a RandomVariable that implicitly depends on a deterministic function of random variables, e.g., `x = Normal(tf.add(z,noise), 0.001)`. If I'm not mistaken, inference would be just as broken, but Edward would not complain. I wonder if there's some way such cases could be detected automatically so an appropriate warning or error can be raised?

This gotcha is hardly unique to Edward, but in my opinion it's a significant gap in the algebra of probabilistic programming that easily trips up new-comers. One of my early memorable experiences with Stan was where I did a power transform but forgot to manually adjust the log probability for the Jacobian of the transformation. For at least some of these cases `TransformedDistribution` is the right solution.

Actually, I'm still a little confused about the exact conditions under which I need to worry about this. Some clarification in the docs would be appreciated:

- which cases Edward can't automatically handle
- when you need to use `TransformedDistribution`
- when you don't need to worry about it

**Comment by jamestwebber** [comment]
> Even more problematic would be if you depended on a RandomVariable that implicitly depends on a deterministic function of random variables, e.g., `x = Normal(tf.add(z,noise), 0.001)`. If I'm not mistaken, inference would be just as broken, but Edward would not complain.

Now that I read this, I worry that I'm doing it in the models I'm building. My impression was that such a case was fine, and in fact part of motivation for using something like edward is that you can build such models. Some guidance on when this is a problem would be much appreciated!

**Comment by dustinvtran** [comment]
> `x = Normal(tf.add(z,noise), 0.001)`

this setting is fine. i guess it depends on what latent variables you're trying to infer: are we asking for the posterior of `z + noise` or is it `z` and `noise` separately? the latter is handled with standard methods, as there's a tractable likelihood and prior. the former goes back to the original problem with an intractable prior.

unless `tf.add(z, noise)` is a `RandomVariable` object (which can be done using `TransformedDistribution`), there is no current way to perform inference on it.  the contract in `ed.Inference()` is that the keys and values in the `latent_vars` dictionary are always `RandomVariable` objects.

i think what you might be getting at is when the latent variables/data arguments can take in tensors and not only `RandomVariable`. when we add such a feature, we'll have to be clear on the conditions you mention.

**Comment by shoyer** [comment]
@dustinvtran OK, glad to hear I was just confused :).
