### ISSUE TITLE
API Inconsistency with TensorFlow 1.0.0rc2

### ISSUE THREAD

**Issue by yyaodong** [blei-lab/edward#451]
Hi,

I recently installed 1.0.0rc2 version of TensorFlow and find there are a lot of API changes in contrib/distributions. For example, parameters of Normal distribution is now "`loc, scale`" instead of "`mu, sigma`", the property of "`is_reparameterized`" changes to "`reparameterization_type`":

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/distributions/python/ops/normal.py

You can find more changes in other distributions as well. These changes in TF largely breaks the consistency with Edward's key inference function.  I was wondering when Edward is going to fit this new version of TF? 

Regards,

**Comment by dustinvtran** [comment]
thanks for asking. this is a high priority for me to fix, which will be completed by the end of today. the `rc2` changed a lot of the distribution API. for now, i recommend using rc0 (not sure if rc1 works).

**Comment by dustinvtran** [comment]
actually, are you sure you're using rc2? here's the commit for `normal.py` in rc2:

https://github.com/tensorflow/tensorflow/blob/1536a84f32f1fe77efd3fee6e5933a1dfe4e10bb/tensorflow/contrib/distributions/python/ops/normal.py

it uses `mu` and `sigma`. it looks like the distribution API changes are on master, but i don't see it for rc2. (i upgraded and ran several edward examples, which worked.)

**Comment by yyaodong** [comment]
I compile the newest master, it still called rc2, but the api are changed

**Comment by dustinvtran** [comment]
yep, got it. i'll work out a separate branch that makes these fixes. it'll be merged whenever the changes make it into a version release, but meanwhile you'll be able to install edward from that branch.
