### ISSUE TITLE
Mixed Effects Model GLMM Examples

### ISSUE THREAD

**Issue by patrickeganfoley** [blei-lab/edward#453]
Hello!  

Would there be any interest in adding some canonical mixed effects model examples?  Maybe something using classic datasets like InstEval (student ratings of instructors, data in the R lme4 package) or the Radon dataset (like @twiecki 's [pym3](http://twiecki.github.io/blog/2014/03/17/bayesian-glms-3/) example).  

They are all pretty simple, but I think having something showing how to use `tf.gather` for id lookups would be helpful.

**Comment by dustinvtran** [comment]
sure, that would be a welcome contribution. none of the current bayesian regression examples are hierarchical (unless you count the [rasch model](https://github.com/blei-lab/edward/blob/master/examples/rasch_model_hmc.py))), so it would also be helpful for that reason. 

with standard normal random effects, it would be very easy to do fast and scalable variational inference. HMC would also work.

**Comment by patrickeganfoley** [comment]
Cool!  Should I keep datasets self contained and simulated, or can I add a csv to `/examples/data` ?

**Comment by dustinvtran** [comment]
real data is preferred. feel free to add it to that directory if there's not a function in another common package that can load it.

**Comment by patrickeganfoley** [comment]
Just opened https://github.com/blei-lab/edward/pull/461 to check if I am in the right direction.  Tried to include some form of criticism (visualization!) for both.
