### ISSUE TITLE
Mixture Density Networks - How do I train the network using Inference/MAP?

### ISSUE THREAD

**Issue by LukeMathWalker** [blei-lab/edward#458]
Hi!

I've been experimenting with Edward to get a MDN model running. I've taken a look at the tutorial and the blog posts available but I'm facing some difficulties in getting rid of model wrappers in the currently available code.

My model definition goes as follows:

```
nb_comp = 20
hidden1 = Dense(15, activation=K.relu)(X)
hidden2 = Dense(15, activation=K.relu)(hidden1)
mus = Dense(nb_comp)(hidden2)
sigmas = Dense(nb_comp, activation=K.exp)(hidden2)
pi = Dense(nb_comp, activation=K.softmax)(hidden2)
c = Categorical(p=pi)
z = Normal(mu=tf.gather(mus, c), sigma=tf.gather(sigmas, c))
```

Now I don't know how to proceed.
I'd like to perform a maximum likelihood estimation of the involved parameters (pi, mus, sigmas) but I don't know how. All my experiments using the MAP class have miserably failed :D

**Comment by dustinvtran** [comment]
Thanks for asking! Re-implementing the MDN has been on my to do list for a while, but kept getting backed up. Motivated to answer your question, I went ahead and finished it. See #459, which has an example. The docs are updated once the PR is merged.

Let me know if this clarifies things.

**Comment by dustinvtran** [comment]
Merged, and rewritten: http://edwardlib.org/tutorials/mixture-density-network
