### ISSUE TITLE
Implementing LDA with Edward

### ISSUE THREAD

**Issue by amit2103** [blei-lab/edward#463]
Is it possible to implement LDA with Edward? We have a large dataset and we want to implement LDA in Tensorflow.  I think Edward should help. I didnt find any implementation of LDA in tensforflow.If any samples is there it will help (We need to do topic modelling )

**Comment by dustinvtran** [comment]
We haven't got around to it because I think the only efficient way to get large-scale LDA working is with coordinate ascent updates. It's easy to write it down but I predict the black box VI currently available will be too slow. This is waiting on making conjugate inference available. (also pinging @matthewdhoffman)

**Comment by amit2103** [comment]
Thanks... This issue talsk of implemnting LDA with Edward :- https://github.com/blei-lab/edward/issues/423
Isnt it using the GPU/Tensorflow? Is it possible to implement LDA the way that pdf doc and the issue suggests?

**Comment by dustinvtran** [comment]
Yes it's using GPU/TensorFlow. The small example in #423 is easy to do. For bigger data, it's the choice of algorithm that's the bottleneck and not the hardware.

**Comment by amit2103** [comment]
Okay...Thanks I am a complete novice and these things are new to me. Will that algorithm work with multiple GPU on AWS EC2 mahines. Thanks for the answers.

**Comment by dustinvtran** [comment]
No problem; thanks for asking. All Edward algorithms are compatible with multiple GPUs.

**Comment by amit2103** [comment]
Thanks..Let me try to implement the LDA, if there is anything, I will contact you guys. Also hopefully Edward will improve its LDA implementations for large data as you mentioned.

**Comment by dustinvtran** [comment]
Cool! Contributions are always welcome, so feel free to submit a pull request that's a work in progress. I'm happy to help work out the LDA details with you.

**Comment by amit2103** [comment]
I will not know where to start. Is it possible to give some starting pointers?  Also how does the current implementation compare with gensim ?

**Comment by dustinvtran** [comment]
You can get started from #423. For syntax, check out the Edward API. http://edwardlib.org/api/

**Comment by amit2103** [comment]
Okay...Cool

**Comment by rw** [comment]
@amit2103 Gensim's LDA is based on this paper, which you may find helpful: https://www.cs.princeton.edu/~blei/papers/HoffmanBleiBach2010b.pdf

@dustinvtran Do you think it would be a good (and feasible) idea to implement complete paper results in Edward, as examples? That seems like the ultimate integration test :-)

**Comment by dustinvtran** [comment]
@rw. Absolutely! In our group, we're using Edward to conduct all experiments with the goal that they'll be open source and super easy to use since they're in/using Edward.

**Comment by XiaoSX** [comment]
@amit2103 hello, I would like to know whether your model is done?actually, I want to do the same thing. Kindly can I have some of your advice, thanks

**Comment by dustinvtran** [comment]
Closing as it's a user-implementation issue. See the Forum's thread for more details (https://discourse.edwardlib.org/t/confused-by-error-message-from-inference-run-for-lda-with-klqp/119); also see duplicates in #423, #473, #476.
