### ISSUE TITLE
hierarchical regression tutorial

### ISSUE THREAD

**Issue by dustinvtran** [blei-lab/edward#470]
building off @patrickeganfoley's work on the [linear mixed effects model](https://github.com/blei-lab/edward/blob/master/examples/linear_mixed_effects_model.py) example, it would be nice to have it (or similar) as a tutorial on the website. hierarchical modeling is an essential for data analysis.

**Comment by patrickeganfoley** [comment]
I'd be happy to put something together like that, or maybe something fitting `y ~ 1 + (1|s) + (1|d) + service + (1 + service|dept)` to show fitting of random slopes.  

It might take me a bit, I'm still thinking about what would be the best way to make it easy to write linear models (producing a design matrix manually v.s. doing something nice that looks a bit more like an lme4 or Patsy formula).

**Comment by patrickeganfoley** [comment]
@dustinvtran Do we care about the size of notebooks?  I am thinking about including some R, could fit the same model in `lme4` w/ `rpy2` and then comparing the fits.

**Comment by dustinvtran** [comment]
Fixed in #539.
