### ISSUE TITLE
InverseGamma-Normal 

### ISSUE THREAD

**Issue by bertini36** [blei-lab/edward#472]
Hi there!

Here you have a InverseGamma-Normal model implementation:
```
# -*- coding: UTF-8 -*-

"""
InverseGamma-Normal model (known mean)
Posterior inference with Edward BBVI
"""

import edward as ed
import numpy as np
import tensorflow as tf
from edward.models import InverseGamma, Normal

N = 1000

# Data generation (known mean)
mu = 7.
sigma = 0.50
xn_data = np.random.normal(mu, sigma, N)
print('sigma={}'.format(sigma))

# Prior definition
alpha = tf.Variable(0.9, dtype=tf.float32, trainable=False)
beta = tf.Variable(0.5, dtype=tf.float32, trainable=False)

# Posterior inference
# Probabilistic model
ig = InverseGamma(alpha=alpha, beta=beta)
xn = Normal(mu=mu, sigma=tf.ones([N]) * ig)

# Variational model
qig = InverseGamma(alpha=tf.nn.softplus(tf.Variable(tf.random_normal([]))),
                   beta=tf.nn.softplus(tf.Variable(tf.random_normal([]))))

# Inference
inference = ed.KLqp({ig: qig}, data={xn: xn_data})
inference.run(n_iter=2000, n_samples=150, logdir='/tmp/train/')

sess = ed.get_session()
print('Inferred sigma={}'.format(sess.run(qig.mean())))
 
```
It seems to converge but when I increase the number of variational model samples in BBVI doesn't improve the approach. Why? Could it be due to the variance introduced by BBVI or to gamma distribution instability? 

If you think it's okay I can make a pull-request for this example.

**Comment by dustinvtran** [comment]
Looks like if you want an inverse gamma posterior you should pass in `sigma=tf.ones(N) * tf.sqrt(ig)` as the likelihood's standard deviation. Fixing this, I still wasn't able to get it to converge to the exact posterior parameters though (or maybe my math calculation is just off).

**Comment by bertini36** [comment]
If you code `sigma=tf.ones(N) * tf.sqrt(ig)`, do you have to put `print('Inferred sigma={}'.format(sess.run(tf.sqrt(qig.mean()))))` too?.
In this way it seems to converge more accurately.

**Comment by dustinvtran** [comment]
Oh of course, good point! Yeah it converges correctly. This would be a welcome example to add to the repo.

**Comment by dustinvtran** [comment]
(In addition, ideally it would be a MCMC example, maybe using e.g., MetropolisHastings or so. This would add a little more diversity to the algorithms that the examples use.)

**Comment by dustinvtran** [comment]
Conjugate prior examples are available in the `tests/test-inferences/test_conjugacy.py` file. Not adding this specifically as the example is pretty trivial. See also [`examples/beta_bernoulli_conjugate.py`](https://github.com/blei-lab/edward/blob/b96ccf9dca0f029015ae102777a56dcd7616e4a3/examples/beta_bernoulli_conjugate.py).

**Comment by gabrielelanaro** [comment]
@bertini36 Is it possible to have a complete working example?

**Comment by dustinvtran** [comment]
see https://github.com/blei-lab/edward/pull/627/commits/9cbd19fac886279a1043c1a4c48cc0462853fd82
