### ISSUE TITLE
[Question] Implementing LDA with edward

### ISSUE THREAD

**Issue by mahatosourav91** [blei-lab/edward#473]
Hi I am trying to implement LDA in tensorflow. I am quite new to both tensorflow and LDA. Currently I am following your lda implementation from [here](https://github.com/arongdari/python-topic-model/blob/master/ptm/lda_vb.py) . But when I tried to implement that using tensorflow I started to get out  of memory errors. I believe that happened because of the  multiple for loops.

Is to possible to implement LDA using edward? I was trying to understand the LDA example from the slides found [here](http://dustintran.com/talks/Tran_Edward.pdf). But I couldn't understand the input dataset or the format of input dataset. Also how to find the document topic distribution ? 

It to would be very helpful if you provide a proper example of LDA with edward with input data set and output.

**Comment by rokgerzelj** [comment]
The code on the LDA slide, in Dustin's presentation you have linked, specifies the joint pdf using Edward's own modelling language. Given that, you would then choose one of Edward's [inference methods](http://edwardlib.org/api/inference-classes). An inference method takes as parameters latent random variables paired with their respective approximate distributions. In your case, that would be the topic per document and word per topic distributions. Besides that, it also takes data for your observed random variables - for LDA, that's the word per document counts.

**Comment by XiaoSX** [comment]
@mahatosourav91 hi, did you fix your problem, kindly can you help me for implementing the LDA with Edward

**Comment by Sachin19** [comment]
@mahatosourav91 Hi, I am also trying to implement a similar model and getting memory errors. Were you able to solve your issue?

**Comment by dustinvtran** [comment]
Closing issue since there's also a related thread on the Forum. I think OP was able to get it to work:

https://discourse.edwardlib.org/t/confused-by-error-message-from-inference-run-for-lda-with-klqp/119
