### ISSUE TITLE
How to install edward with tensorflow-gpu

### ISSUE THREAD

**Issue by shixiazuike** [blei-lab/edward#481]
When install edward via
```bash
>>> pip install edward
```
it will install tensorfow and cover tensorflow-gpu as the requirments list

**Comment by dustinvtran** [comment]
Thanks for this! I'm submitting a bug fix now. It should make it into the next Edward version. The problem is that TensorFlow uses two python packages which ruins the ability to have it as a dependency.

For now if you know you have a compatible TensorFlow version (`>=1.0.0a0`), try:
```python
pip install --no-deps edward
```
