### ISSUE TITLE
Suggestion: Add a API reference page

### ISSUE THREAD

**Issue by chmp** [blei-lab/edward#502]
In its current form, the documentation of edward is outstanding, when read in order. However, when read out of order, it can be difficult to find the right page. I like to suggest adding an index / reference page, collecting links to all documented functions. 

This suggestion may have overlap with #496 and #497.

**Comment by dustinvtran** [comment]
Thanks. I've been thinking hard about this problem. The difficulty is in managing two sidebars, both on the left for browsing the website, and on the top for browsing the API.

Maybe the solution is to replace the current sidebar with the top sidebar, for the API. They can still navigate to other aspects of the website via clicking the Edward logo or a big "Home" button. We can then add a top sidebar for even more fine-grained navigation.

**Comment by chmp** [comment]
I have to admit, I wasn't as ambitious :). My idea was just to add a new page, which has a list of all all classes available, linking into other existing docs. Since edward is quite lean, it should be usable without further subdivisions. I started with it, but then prioritized looking into #525. If you want to I can open a PR with my unfinished draft.

It looks like that at the moment:

![edward_reference](https://cloud.githubusercontent.com/assets/949987/23821368/6993825c-0630-11e7-8741-ee058220e14b.png)

The links are working. The stylesheet is clearly not ;). As for the implementation overhead, it is minimal since sphinx is doing all the heavy lifting in cross-referencing the docs.

**Comment by dustinvtran** [comment]
Cool! Mind sending a (work in progress) PR? I'd like to browse it a bit to see how it might be improved.

**Comment by chmp** [comment]
Done. Looking over the code, it seems they are minimal indeed.

**Comment by dustinvtran** [comment]
Added in #536.
