### ISSUE TITLE
hacks to sample from distributions in tensorflow

### ISSUE THREAD

**Issue by dustinvtran** [blei-lab/edward#51]
I'm not sure how much this affects our current runtimes, but right now, in order to sample from q, we have to run the session to realize the variational parameters and then sample using scipy.

TensorFlow supports uniform and standard normal, and from there we can try to use clever hacks in the literature to get fast and numerically stable samples from other distributions (Devroye, 1986?). Here are some off the top of my head:

- [ ] Uniform (built-in)
- [ ] Normal (location-scale transform of `tf.random_normal`)
- [ ] Multivariate Normal (location-scale transform of `tf.random_normal`)
- [ ] Log-Normal (sample from normal, then exp() transform it)
- [ ] [Bernoulli](http://stackoverflow.com/questions/35487598/sampling-bernoulli-random-variables-in-tensorflow) (`tf.select` from a uniform)
- [ ] [Multinomial](https://github.com/tensorflow/tensorflow/issues/456#issuecomment-164038802) (Gumbel arg max trick)
- [ ] Exponential (`eps ~ Unif(0,1)`, `log(1/eps)` transform it)
- [ ] Inverse Gamma (sample from Gamma, then 1/() transform it)

References
* http://blog.shakirm.com/2015/10/machine-learning-trick-of-the-day-4-reparameterisation-tricks/
* Devroye, L. (1996). Random variate generation in one line of code (pp. 265–272). IEEE. http://doi.org/10.1109/WSC.1996.873288

**Comment by akucukelbir** [comment]
i recommend always checking how Stan math implements these; numerical stability is easy to overlook.

https://github.com/stan-dev/math/tree/develop/stan/math/prim/scal/prob

**Comment by altosaar** [comment]
tf.contrib.distributions has many of these

**Comment by dustinvtran** [comment]
As @altosaar said, `tf.contrib.distributions` has quite a few of these and is making active progress in a robust distributions library. I'll leave this issue open but it's worth noting that we don't have to work on this and can wait on native TensorFlow development instead.

**Comment by dustinvtran** [comment]
Following #237, we now rely on `tf.contrib.distributions` to do the right TensorFlow sampling.

**Comment by bashhwu** [comment]
Hi Dustin,

Suppose you have a pdf for an unknown distribution.  How to sample from this distribution? 
I tried MCMC and Inverse CDF but they are so slow. Any idea?

**Comment by dustinvtran** [comment]
That's a very hard problem in general. Perhaps look into sampling from undirected models or energy-based models.

**Comment by bashhwu** [comment]
what about developing custom distribution in edward? does it solve it if I
I have the pdf formula?

**Comment by bashhwu** [comment]
Any plan to add Exponentially modified Gaussian and Skew Gaussian distributions to Edward? like Scipy?
