### ISSUE TITLE
Will it support Stochastic Process in future?

### ISSUE THREAD

**Issue by Xeclipse** [blei-lab/edward#512]
It's an amazing tool! I want to know will it support Stochastic Process like Dirichlet Process, Gaussian Process in future? Since tensorflow doesn't provide these api, I wonder that will you develop it. :)

**Comment by dustinvtran** [comment]
Thanks for asking. It's on the roadmap but not a priority (https://github.com/blei-lab/edward/issues/464). However, just yesterday for example, I added the key pieces for implementing a Dirichlet process random variable in Edward (https://github.com/blei-lab/edward/pull/508). The remaining work would be to properly write a class `DirichletProcess` that uses it for sampling.

**Comment by dustinvtran** [comment]
Moving discussion to http://discuss.edwardlib.org/t/will-it-support-stochastic-process-in-future/25.
