### ISSUE TITLE
ImportError: cannot import name 'MultivariateNormalCholesky'

### ISSUE THREAD

**Issue by sshidy** [blei-lab/edward#521]
>>> import edward
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\winpy3\python-3.5.3.amd64\lib\site-packages\edward\__init__.py", line 6, in <modul
e>
    from edward import inferences
  File "D:\winpy3\python-3.5.3.amd64\lib\site-packages\edward\inferences\__init__.py", line 1
1, in <module>
    from edward.inferences.laplace import *
  File "D:\winpy3\python-3.5.3.amd64\lib\site-packages\edward\inferences\laplace.py", line 9,
 in <module>
    from edward.models import \
ImportError: cannot import name 'MultivariateNormalCholesky'

**Comment by dustinvtran** [comment]
Can you report your versions? My guess is you need to upgrade `tensorflow>=1.0.0a0`.

**Comment by sshidy** [comment]
installed tensorflow_gpu-1.0.0-cp35-cp35m-win_amd64.whl
VERSION
    1.0.0
edward 1.2.3, installed simly by "pip install edward"

**Comment by dustinvtran** [comment]
Can you try the following?
```python
from tensorflow.contrib.distributions import MultivariateNormalCholesky
```
This should exist in TensorFlow v1.0.0, as indicated in the [v1.0 source](https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/contrib/distributions/python/ops/mvn.py#L551).

**Comment by sshidy** [comment]
I tried, import error. That could be problems of tensorflow version in windows. I will work on linux.

**Comment by sshidy** [comment]
It doesn't work. And I cannot find MultivariateNormalCholesky by filefinder in https://github.com/tensorflow/tensorflow
Is it possible that tensorflow does not support it now?

**Comment by dustinvtran** [comment]
TensorFlow doesn't have it in their master branch anymore (some of the API changed), although they definitely still have it in 1.0.1 and 1.0.0. Were you using a development version of TensorFlow? If so, Edward won't be updated to reflect those changes until they make it into a version release (#452).

**Comment by sshidy** [comment]
updated to tensorflow 1.0.1, problem solved. Thank you!

**Comment by dustinvtran** [comment]
Great!

**Comment by tigerneil** [comment]
@sshidy I try it today in windows, but still can't import `'MultivariateNormalCholesky`. I check tensorflow version is 1.0.1 
```
ImportError                               Traceback (most recent call last)
<ipython-input-20-0314a5faf0d1> in <module>()
----> 1 import edward

C:\Users\neil\Anaconda3\envs\tensorflow35\lib\site-packages\edward\__init__.py in <module>()
      4
      5 from edward import criticisms
----> 6 from edward import inferences
      7 from edward import util
      8

C:\Users\neil\Anaconda3\envs\tensorflow35\lib\site-packages\edward\inferences\__init__.py in <module>()
      9 from edward.inferences.klpq import *
     10 from edward.inferences.klqp import *
---> 11 from edward.inferences.laplace import *
     12 from edward.inferences.map import *
     13 from edward.inferences.metropolis_hastings import *

C:\Users\neil\Anaconda3\envs\tensorflow35\lib\site-packages\edward\inferences\laplace.py in <module>()
      7
      8 from edward.inferences.map import MAP
----> 9 from edward.models import \
     10     MultivariateNormalCholesky, MultivariateNormalDiag, \
     11     MultivariateNormalFull, PointMass, RandomVariable

ImportError: cannot import name 'MultivariateNormalCholesky'

In [21]: from tensorflow.contrib.distributions import MultivariateNormalCholesky
    ...:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-21-176aeb57a3e6> in <module>()
----> 1 from tensorflow.contrib.distributions import MultivariateNormalCholesky

ImportError: cannot import name 'MultivariateNormalCholesky'

In [22]: import tensorflow

In [23]: tensorflow.__version__
Out[23]: '1.0.1'

In [24]:
```

**Comment by dustinvtran** [comment]
Are you using a development version of TensorFlow? If you're using a stable release of 1.0.1 then you should be fine, as per the discussion above.

**Comment by olegsinyavskiy** [comment]
The issue reappeared with tensorflow==1.1.0. Solution is still valid: downgrade to 1.0.1

**Comment by dustinvtran** [comment]
Right. We noted this in the [troubleshooting](http://edwardlib.org/troubleshooting) page. If you aim to use TensorFlow==1.1.0, you need to install a particular branch of Edward (page has details).
