### ISSUE TITLE
Saving Model Parameters

### ISSUE THREAD

**Issue by GhassanMakhoul** [blei-lab/edward#535]
I am working on a variational inference problem, and was wondering how I could snapshot the weights after training. I want to be able to restore then query 'q', my approximation distribution, and draw samples from it. I am familiar with saving variables with tf.train.saver. Is there a similarly easy way to save the parameters of my inference model?

**Comment by dustinvtran** [comment]
hi @GhassanMakhoul | `tf.train.Saver` applies to variational approximations too. In your code, you should be handling your own tf variables to parameterize your inference model. After (or during) inference, you can call, e.g.,
```python
saver = tf.train.Saver()

sess = ed.get_session()
save_path = saver.save(sess, "/tmp/posterior.ckpt")
print("Model saved in file: %s" % save_path)
```
which is the [same way you would save model parameters in TensorFlow](https://www.tensorflow.org/versions/master/how_tos/variables/).

**Comment by dustinvtran** [comment]
Does this answer your question? Closing issue. Feel free to continue the discussion on the newly formed [Edward Forum](http://discuss.edwardlib.org).

**Comment by TheG3ntl3man** [comment]
Hi, this works good for me I can restore the variables and recreate the model after, but I have a dictionary of several Neural networks (each entry in the dict has a inference object and posterior weights) and I want to be able to save and restore that dictionary to then use those nn, to retrain them, predict, etc, do you know how I can do that?

**Comment by omarperezr** [comment]
Hello, after I restore the weights how do I rebuild my inference?

**Comment by pswpswpsw** [comment]
But it does not save the RandomVariables, it only saves the tensorflow variable which is the paramete of the random variables. This is kind of painful that one cannot really import the graph, the meta data, and the parameters and then simply *sess.run(..., feed_dict={...})* to obtain the model. 

Is that correct? How to deal with it then? Is it possible to have something like tensorflow save model API?

**Comment by omarperezr** [comment]
Yeah, like I managed to save all of the tensors and then I rebuilt all of the posterior weights and with that I can predict, but to train on new data I made something like this

inference = ed.KLqp({qW_0: qW_0, qb_0: qb_0,
                                 qW_1: qW_1, qb_1: qb_1,
                                 qW_2: qW_2, qb_2: qb_2},
                                 data={X: new_data_to_train_with, y: target_of_new_data}) # Rebuilding inference object

inference.run(n_iter=100, optimizer=optimizer, global_step=global_step) # Optimizing with new data

And I guess It works, but isn't there a better way?

(all of this {qW_0: qW_0, qb_0: qb_0,
                                 qW_1: qW_1, qb_1: qb_1,
                                 qW_2: qW_2, qb_2: qb_2} are the posterior weights and biases from the previous training)
