### ISSUE TITLE
Add HTTPS support to discuss.edwardlib.org

### ISSUE THREAD

**Issue by rw** [blei-lab/edward#537]
Generally this is a good idea for all websites :-)

**Comment by dustinvtran** [comment]
Good idea. I'll look into this, and SSL also for edwardlib.org.

**Comment by rw** [comment]
Without knowing your particular hosting situation, I can't recommend a specific way to do it. However, it's a good bet you'll find Let's Encrypt useful.

**Comment by dustinvtran** [comment]
We host edwardlib.org with Github pages. It doesn't look like HTTPS is supported for Github pages with custom domains. [[source]](https://help.github.com/articles/securing-your-github-pages-site-with-https/). Cloudflare works but I don't want a middleman.

We host discuss.edwardlib.org via Discourse. It looks possible; I'll e-mail them.

**Comment by dustinvtran** [comment]
I was able to get free SSL support, although the subdomain has now been moved to https://discourse.edwardlib.org. Huge thanks for the excellent and very responsive Discourse support!
