### ISSUE TITLE
InternalError in GAN example

### ISSUE THREAD

**Issue by reinheimer** [blei-lab/edward#578]
I've recently tried to run the [GAN example](http://edwardlib.org/tutorials/gan) in Jupyter and came across [this error](https://github.com/blei-lab/edward/files/865530/gan.zip) while training:

```
...
InternalError (see above for traceback): Blas SGEMM launch failed : a.shape=(128, 100), b.shape=(100, 128), m=128, n=128, k=100
	 [[Node: Gen/fully_connected/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](Gen/Uniform/sample/Reshape, Gen/fully_connected/weights/read)]]
```
Online, I found it could be due to multiple instances competing for the GPU ([1](http://stackoverflow.com/questions/37337728/tensorflow-internalerror-blas-sgemm-launch-failed)). I closed every other session, restarted the Jupyter notebook kernel and tried to rerun everything, but to no avail.

The same example, when run on terminal (I used `ipython gan.py`), seems to work properly, as it stores the generated images of digits in a directory.

Settings: 
- macOS Sierra 10.12.3
- venv from Python 3.4.2
- tensorflow-gpu 1.0.1
- edward 1.2.4
- Jupyter 1.0.0 (core 4.3.0, client 5.0.0, console 5.1.0)
- IPython 5.3.0
- CUDA 8.0 and cuDNN 5.1

[This](http://stackoverflow.com/questions/42314449/tensorflow-jupyter-multiple-sessions-throwing-blas-sgemm-launch-failed) highlights Tensorflow as the source, but I could not find the follow up for the question.

Thank you in advance!

**Comment by dustinvtran** [comment]
Do you know if you're able to run vanilla TensorFlow scripts? This could help diagnose if it's TensorFlow or an Edward problem.

http://stackoverflow.com/questions/37337728/tensorflow-internalerror-blas-sgemm-launch-failed also seems relevant.

**Comment by reinheimer** [comment]
Hello,
Would you recommend any particular script?
I tried running [this](https://github.com/aymericdamien/TensorFlow-Examples/blob/master/notebooks/3_NeuralNetworks/recurrent_network.ipynb), with the same error, now on "Node: rnn/basic_lstm_cell/basic_lstm_cell/MatMul".

[Here](https://github.com/blei-lab/edward/files/905780/lstm.zip) is the complete notebook with the traceback.

Thank you very much for your attention.

**Comment by dustinvtran** [comment]
This is an issue in the TensorFlow install. I'm not an expert in this unfortunately, so you might try raising the same issue on https://github.com/tensorflow/tensorflow/issues or StackOverflow.
