### ISSUE TITLE
Edward not matching theory

### ISSUE THREAD

**Issue by timothy-shields** [blei-lab/edward#587]
Consider the following program:

```
import edward as ed
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from edward.models import Bernoulli, Beta

sess = ed.get_session()
tf.global_variables_initializer().run()

x_data = np.array(90 * [0] + 10 * [1])

p = Beta(a=1.0, b=1.0)
x = Bernoulli(p=tf.ones(len(x_data)) * p)

qp = Beta(a=tf.nn.softplus(tf.Variable(0.0)),
          b=tf.nn.softplus(tf.Variable(0.0)))

inference = ed.KLqp({p: qp}, data={x: x_data})
inference.run()

print('Posterior: Beta({:.2f}, {:.2f})'.format(qp.a.eval(), qp.b.eval()))

xs = np.linspace(0, 1, 1000, dtype=np.float32)
plt.plot(xs, p.pdf(xs).eval(), label='prior')
plt.plot(xs, qp.pdf(xs).eval(), label='posterior')
plt.legend()
plt.show()
```

I am getting the following output:

`Posterior: Beta(0.69, 4.31)`

![image](https://cloud.githubusercontent.com/assets/3581591/24300239/c8ded678-1079-11e7-856b-e9101bd520a3.png)

But the posterior Beta distribution after observing A 1's and B 0's should be Beta(1+A, 1+B) based on the prior Beta(1, 1), so I would expect the following output:

`Posterior: Beta(11.00, 91.00)`

![image](https://cloud.githubusercontent.com/assets/3581591/24300345/323f016a-107a-11e7-917c-2b6f47b6c1ba.png)

How can I obtain the expected output?

**Comment by dustinvtran** [comment]
`inference.run()` runs for a fixed number of iterations. See [its API](http://edwardlib.org/api/inference.html#edward.inferences.Inference). To obtain the true posterior, you'll need to run it longer and monitor convergence.

**Comment by timothy-shields** [comment]
@dustinvtran After one million iterations I still get Beta(1.16, 6.45) as the posterior.
