### ISSUE TITLE
write tests for functions in edward/util.py

### ISSUE THREAD

**Issue by akucukelbir** [blei-lab/edward#60]
there are many small functions in `edward/util.py` that we depend on.

let's write unit tests for them.

**Comment by dustinvtran** [comment]
+ `test_cumprod.py`
+ `test_get_session.py`
+ `test_kl_multivariate_normal.py`
+ `test_logit.py`
+ `test_multivariate_rbf.py`
+ `test_rbf.py`
+ `test_set_seed.py`
+ `test_softplus.py`
+ `test_stop_gradient.py`
+ `test_to_simplex.py`
