### ISSUE TITLE
ImportError: No module named stats (norm.logpdf)

### ISSUE THREAD

**Issue by mingwugmail** [blei-lab/edward#601]
Hi,

I'm following:

https://github.com/cbonnett/MDN_Edward_Keras_TF/blob/master/MDN_Edward_Keras_TF.ipynb

from edward.stats import norm # normal distribution from Edward ! 
ImportError: No module named stats

somewhere it calls:

result = tf.exp(norm.logpdf(y, self.mus, self.sigmas))

I searched logpdf in edward, but didn't find it.

It's gone?

**Comment by dustinvtran** [comment]
That tutorial is out of date. It's updated [here](http://edwardlib.org/tutorials/mixture-density-network); a link to the corresponding notebook is also in that link.
