### ISSUE TITLE
KLqp.kl_scaling is neglected.

### ISSUE THREAD

**Issue by fujiisoup** [blei-lab/edward#638]
Hi.

I think `KLqp.kl_scaling` is simply neglected if there are some random distributions other than Normal.
Is it designed behavior?

I think scaling KL term is possible even for non-analytic KL term and at least it should raise an Error.

**Comment by dustinvtran** [comment]
You are correct. KL scaling only works for normal distributions. 

I also agree; we should raise, say, in `build_loss_and_gradients()` when using a non-analytic KL method and `kl_scaling is not None`. Contributions welcome.

**Comment by dustinvtran** [comment]
Fixed in #672.
