### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by jcapde87** [blei-lab/edward#64]
Congrats Dustin for Edward! It seems very promising for easing the inference of probabilistic models. 

I've seen that documentation is in progress, but let me report a couple of things, in case you'd like to fix. 
In Tutorial for Research there's a wrong link which points to stan example instead of Tf.
"Here is a toy script that uses this model which is written in TensorFlow."

and where you say _Numpy/SciPy, I guess that you refer to _Stan, since the link points to stan and Numpy/SciPy example is above.
"Here is another toy script that uses the same model written in _NumPy/SciPy_."

**Comment by dustinvtran** [comment]
Fixed. Thanks!
