### ISSUE TITLE
ed.KLqp break due to the API change of tensorflow

### ISSUE THREAD

**Issue by Vandermode** [blei-lab/edward#640]
Run the code as follows will raise AttributeError
```
inference = ed.KLqp({W_0: qW_0, b_0: qb_0,
                     W_1: qW_1, b_1: qb_1}, data={y: y_train})
inference.run(n_iter=1000, n_samples=5)
```
AttributeError: module 'tensorflow.contrib.distributions' has no attribute 'kl'.

I check the API of tensorflow to find tensorflow.contrib.distributions.kl has changed its name to kl_divergency. Consequently simply adding `tf.contrib.distributions.kl = tf.contrib.distributions.kl_divergence` will work fine. But in the long term,  the API name should be fixed in edward.

**Comment by rachtsingh** [comment]
This broke for me as well - is there any way to pin the version of Tensorflow in case of other similar changes in the future? Or at least edit http://edwardlib.org/troubleshooting to be "TensorFlow (=1.1.0rc0)" for now, until the API stabilizes?

**Comment by dustinvtran** [comment]
It looks like `tf.contrib.distributions` is moving in general to TensorFlow core. This makes some of the rc versions of TensorFlow 1.2.0 a little wonky. For now, I recommend sticking to 1.1.0. A work-in-progress PR is made for this issue (https://github.com/blei-lab/edward/pull/656).

@rachtsingh Done.

**Comment by rachtsingh** [comment]
Great, thank you! (and thanks for Edward, it's a great library)
