### ISSUE TITLE
More Criticism (comparison to lme4) for Mixed Effects Model

### ISSUE THREAD

**Issue by patrickeganfoley** [blei-lab/edward#650]
Hello!

I just compared the mixed effects model example (https://github.com/blei-lab/edward/blob/master/notebooks/linear_mixed_effects_models.ipynb) to the same model in `lme4`, and was please to see they agree!  (I had checked b/c a very similar model looked like it wasn't converging.)

The instructor random effects, after 100 iterations, compared to those found by `lme4`:

![instructor_comparison_100](https://cloud.githubusercontent.com/assets/5103389/26518260/c693dab6-4261-11e7-8f1a-d32f972a07ce.png)

And the same comparison, after 10,000 iterations:

![instructor_comparison_10k](https://cloud.githubusercontent.com/assets/5103389/26518261/d2a3d284-4261-11e7-8919-a9885f7cf668.png)

Would it be cool if I added this comparison to the tutorial?

**Comment by dustinvtran** [comment]
Yes! :)

**Comment by patrickeganfoley** [comment]
Great!  I could either upload a cvs of the random effects fit by lme4, or call rpy2 within the notebook.  

Cool if I put the fit effects in /examples/data, or is there a better place?

**Comment by dustinvtran** [comment]
That's fine for now. I think we'll eventually have an individual data subdirectory in `notebooks/`.

**Comment by patrickeganfoley** [comment]
Cool!  Just opened a pr - https://github.com/blei-lab/edward/pull/655

**Comment by dustinvtran** [comment]
Fixed in #655.
