### ISSUE TITLE
ImportError: cannot import name kl_divergence. Your TensorFlow version is not supported.

### ISSUE THREAD

**Issue by TheShadow29** [blei-lab/edward#689]
Tensorflow version : '1.1.0'
Python : '2.7.12'
Code : 
```
import tensorflow as tf
import edward
```
Gives output : 
![screenshot from 2017-06-22 12-08-56](https://user-images.githubusercontent.com/10602903/27451351-96e60054-5743-11e7-9c8c-8238125e0839.png)

What are my possible options? What version should the tensorflow be? Can this be added to the exception raised?

**Comment by dustinvtran** [comment]
You need 1.2.0. It's written on the website (http://edwardlib.org/getting-started). We avoid hard-coding this in TensorFlow as the import error can arise for other reasons not specific to 1.2.0.

**Comment by TheShadow29** [comment]
Damn it. I must be blind. For some reason I missed the bold part. Sorry for the silly question.
