### ISSUE TITLE
importance weighted autoencoders

### ISSUE THREAD

**Issue by dustinvtran** [blei-lab/edward#69]
>On May 7, 2016, at 11:27 AM, Rick Farouni <rfarouni@gmail.com> wrote:
>
>Hi Dustin,
>
>Is it straightforward to implement  importance weighted autoencoders in Edward? 
>
>Thanks 
>Rick Farouni,
>http://rfarouni.github.io/

Yes this is straightforward. I think this could be a useful example to put in the `examples/` directory, as it is a simple extension of mean-field variational inference, and the example would showcase how to develop new inference algorithms for conducting research in Edward.

The built-in `MFVI` algorithm is a bit complex to look at, as it automates the choice of the loss function depending on whether certain terms in the variational objective are tractable (such as whether to use analytic entropies or do reparameterization). But if you take a look at one of those `build_loss()` methods there, you can easily tweak it to incorporate the importance weighted loss that is used in IWAEs.

(I imagine the example file would build this inference algorithm and then run it on a toy model. We can think about putting a more complex/automated version of this as one of the built-in inference algorithms if it's a popular request.)

**Comment by rfarouni** [comment]
I see. I will look into how to get it implemented. Thanks for the clarification!
