### ISSUE TITLE
GPU running doesn't show speedup for irt.py example

### ISSUE THREAD

**Issue by leocnj** [blei-lab/edward#698]
I compared irt.py example code on both CPU and GPU (Titan X). To make the task more complicate than the one in the Edward repository, I updated the toy data set generation to 

`n_students = 50000000
n_questions = 200000
n_obs = 2000000`

It was surprising to find that both running modes lasted about 3300 seconds - the speedup of using GPU cannot be observed. Any thought ?

Thanks.

**Comment by dustinvtran** [comment]
Can you verify that the GPU was turned on? There should be a significant difference between the two.

**Comment by leocnj** [comment]
Yes. I used nvidia-smi and can see that GPUs have been used. Will do more careful checks and keep  you informed. Thanks.

**Comment by dustinvtran** [comment]
I confirm that with the above settings, a Titan X (Pascal) GPU returns
```
50/50 [100%] ██████████████████████████████ Elapsed: 8s | Loss: 10426302.000
```
In contrast, a Xeon E5-2630 v3 CPU (2.40Ghz) returns
```
50/50 [100%] ██████████████████████████████ Elapsed: 54s | Loss: 10427964.000
```
So there's roughly a 7x speedup.

**Comment by leocnj** [comment]
Just realized that I need to remove time-consuming figure plotting I/O part. After removing that portion, I got the result very similar to yours

On a Titan X (Maxwell) GPU 
`50/50 [100%] ██████████████████████████████ Elapsed: 7s | Loss: 10427182.000`
On Intel(R) Xeon(R) CPU E5-1660 v3 @ 3.00GHz
`50/50 [100%] ██████████████████████████████ Elapsed: 47s | Loss: 10426520.000`

It is very impressive to see such scale speed-up by simply turning on GPUs.

**Comment by tscholak** [comment]
@leocnj @dustinvtran I tried to reproduce your results on my laptop.
With a 1080 TI (Pascal) connected via Thunderbolt 3 I consistently get
`50/50 [100%] ██████████████████████████████ Elapsed: 10s | Loss: 10427206.000`
I wonder how much of that extra time is due to:
* detrimental Thunderbolt 3 link speed (see CUDA-Z report below),
* the mac os factor (I guess you are running this on linux), and
* whether or not the higher double-precision performance of the Titans plays any role here (probably not, because everything I see is float32).

Could you run CUDA-Z (http://cuda-z.sourceforge.net/) on your machine(s)?

```
CUDA-Z Report
=============
Version: 0.10.251 64 bit http://cuda-z.sf.net/
OS Version: Mac OS X 10.12.4 16E195
Driver Version: 10.16.34 355.10.05.35f05
Driver Dll Version: 8.0
Runtime Dll Version: 6.50

Core Information
----------------
	Name: GeForce GTX 1080 Ti
	Compute Capability: 6.1
	Clock Rate: 1582 MHz
	PCI Location: 0:196:0
	Multiprocessors: 28
	Threads Per Multiproc.: 2048
	Warp Size: 32
	Regs Per Block: 65536
	Threads Per Block: 1024
	Threads Dimensions: 1024 x 1024 x 64
	Grid Dimensions: 2147483647 x 65535 x 65535
	Watchdog Enabled: Yes
	Integrated GPU: No
	Concurrent Kernels: Yes
	Compute Mode: Default
	Stream Priorities: Yes

Memory Information
------------------
	Total Global: 10.9998 GiB
	Bus Width: 352 bits
	Clock Rate: 5505 MHz
	Error Correction: No
	L2 Cache Size: 48 KiB
	Shared Per Block: 48 KiB
	Pitch: 2048 MiB
	Total Constant: 64 KiB
	Texture Alignment: 512 B
	Texture 1D Size: 131072
	Texture 2D Size: 131072 x 65536
	Texture 3D Size: 16384 x 16384 x 16384
	GPU Overlap: Yes
	Map Host Memory: Yes
	Unified Addressing: Yes
	Async Engine: Yes, Bidirectional

Performance Information
-----------------------
Memory Copy
	Host Pinned to Device: 1461.63 MiB/s
	Host Pageable to Device: 1479.61 MiB/s
	Device to Host Pinned: 2532.28 MiB/s
	Device to Host Pageable: 2475.09 MiB/s
	Device to Device: 143.903 GiB/s
GPU Core Performance
	Single-precision Float: 12.7486 Tflop/s
	Double-precision Float: 421.696 Gflop/s
	64-bit Integer: 937.963 Giop/s
	32-bit Integer: 4351.58 Giop/s
	24-bit Integer: 3260.06 Giop/s

Generated: Fri Jul  7 08:06:17 2017
``

**Comment by leocnj** [comment]
Sorry for the late response. See the CUDA-Z report from my Linux machine. 

`
CUDA-Z Report

Version: 0.10.251 64 bit http://cuda-z.sf.net/
OS Version: Linux 3.13.0-110-generic #157-Ubuntu SMP Mon Feb 20 11:54:05 UTC 2017 x86_64
Driver Version: 375.66
Driver Dll Version: 8.0 (375.66)
Runtime Dll Version: 6.50

Core Information
----------------
	Name: GeForce GTX TITAN X
	Compute Capability: 5.2
	Clock Rate: 1076 MHz
	PCI Location: 0:6:0
	Multiprocessors: 24 (3072 Cores)
	Threads Per Multiproc.: 2048
	Warp Size: 32
	Regs Per Block: 65536
	Threads Per Block: 1024
	Threads Dimensions: 1024 x 1024 x 64
	Grid Dimensions: 2147483647 x 65535 x 65535
	Watchdog Enabled: No
	Integrated GPU: No
	Concurrent Kernels: Yes
	Compute Mode: Unknown
	Stream Priorities: Yes

Memory Information
------------------
	Total Global: 11.9211 GiB
	Bus Width: 384 bits
	Clock Rate: 3505 MHz
	Error Correction: No
	L2 Cache Size: 48 KiB
	Shared Per Block: 48 KiB
	Pitch: 2048 MiB
	Total Constant: 64 KiB
	Texture Alignment: 512 B
	Texture 1D Size: 65536
	Texture 2D Size: 65536 x 65536
	Texture 3D Size: 4096 x 4096 x 4096
	GPU Overlap: Yes
	Map Host Memory: Yes
	Unified Addressing: Yes
	Async Engine: Yes, Bidirectional

Performance Information
-----------------------
Memory Copy
	Host Pinned to Device: 5882.65 MiB/s
	Host Pageable to Device: 5364.27 MiB/s
	Device to Host Pinned: 6276.3 MiB/s
	Device to Host Pageable: 6021.04 MiB/s
	Device to Device: 114.863 GiB/s
GPU Core Performance
	Single-precision Float: 6862.43 Gflop/s
	Double-precision Float: 219.927 Gflop/s
	64-bit Integer: 460.101 Giop/s
	32-bit Integer: 2279.51 Giop/s
	24-bit Integer: 1668.65 Giop/s

Generated: Mon Aug 28 15:03:34 2017

`
