### ISSUE TITLE
Tutorial example example fails if run more than once

### ISSUE THREAD

**Issue by RMKD** [blei-lab/edward#70]
https://github.com/blei-lab/edward/wiki/Tutorial
- execute example code
- execute `inference.run(n_iter=10000)`

```
KeyError: "Registering two gradient with name 'temp' !(Previous registration was in <module> ~/.virtualenvs/aws/lib/python2.7/site-packages/ipykernel/__main__.py:3)"
```

(this showed up when running the code in separate cells in a jupyter notebook)

**Comment by dustinvtran** [comment]
Hi @RMKD, thanks for reporting the bug. I'm unable to reproduce it unfortunately but I'm hoping the commit above fixes it. Can you try installing the development version and see if there's still an error?
```
pip install -e "git+https://github.com/blei-lab/edward.git#egg=edward"
```
