### ISSUE TITLE
Hyperlink to data unit test 404s

### ISSUE THREAD

**Issue by matthewfeickert** [blei-lab/edward#709]
Hi. On the API and Documentation [Data webpage](http://edwardlib.org/api/data) at the bottom there is the sentence
>As an example, see the [data unit test](https://github.com/blei-lab/edward/blob/master/tests/test-inferences/test_data.py).

However, the link (https://github.com/blei-lab/edward/blob/master/tests/test-inferences/test_data.py) 404s as the file name has changed from `test_data.py` to [`test_inference_data.py`](https://github.com/blei-lab/edward/blob/master/tests/test-inferences/test_inference_data.py).

**Comment by dustinvtran** [comment]
Good catch. Pull request changing the link is welcome.
