### ISSUE TITLE
Help for example irt.py

### ISSUE THREAD

**Issue by xxxspy** [blei-lab/edward#721]
I'm trying to understand the example [edward/examples/irt.py](https://github.com/blei-lab/edward/blob/30c4308f811797dd785e9e3df13fa67bfabf89cc/examples/irt.py). Unfortunately, I'm still confusing. Is there any references or materials about the algorithm ? Any help would be appreciated.

**Comment by dustinvtran** [comment]
User Q&A is recommended at https://discourse.edwardlib.org. The most related documentation is likely the [linear mixed effects model tutorial](http://edwardlib.org/tutorials/linear-mixed-effects-models).
