### ISSUE TITLE
AttributeError: module 'keras.backend' has no attribute 'set_session'

### ISSUE THREAD

**Issue by CoderCoderCoder** [blei-lab/edward#723]
Hello,
I am trying to execute your example, namely this line of code:

```
inference = ed.KLqp({W_0: qW_0, b_0: qb_0,
                     W_1: qW_1, b_1: qb_1}, data={y: y_train})
```

But unfortunately I see this error:

```
 File "<ipython-input-4-3c0965890976>", line 2, in <module>
    W_1: qW_1, b_1: qb_1}, data={y: y_train})

  File "/Users/a/anaconda/lib/python3.6/site-packages/edward/inferences/klqp.py", line 59, in __init__
    super(KLqp, self).__init__(*args, **kwargs)

  File "/Users/a/anaconda/lib/python3.6/site-packages/edward/inferences/variational_inference.py", line 32, in __init__
    super(VariationalInference, self).__init__(*args, **kwargs)

  File "/Users/a/anaconda/lib/python3.6/site-packages/edward/inferences/inference.py", line 66, in __init__
    sess = get_session()

  File "/Users/a/anaconda/lib/python3.6/site-packages/edward/util/graphs.py", line 42, in get_session
    K.set_session(_ED_SESSION)

AttributeError: module 'keras.backend' has no attribute 'set_session'
```

Python 3.6 on Anaconda, latest Edward+Keras+Tensorflow installed through PIP. MacOS 10.12.6.

Please advise, thanks.

**Comment by dustinvtran** [comment]
To confirm, this is Keras 2.0.6? Can you try

```python
from keras import backend as K
K.set_session
```
You should see
```
Using TensorFlow backend.
<function set_session at 0x11a6466e0>
```

**Comment by CoderCoderCoder** [comment]
Indeed, it was configured to use Theano, my bad!

**Comment by ashleshsortee** [comment]
How do you solve this @CoderCoderCoder.
Please help me.
Thanks in advance.

**Comment by Akshaypatil15** [comment]
try with
>>> import keras.backend.tensorflow_backend as K
and then try
>>> K.set_session
<function set_session at 0x7f88fde5dae8>

**Comment by Akshaypatil15** [comment]
@ashleshsortee 
Try to import 
`
import keras.backend.tensorflow_backend as K
`
and then
`
K.set_session
`
you will get output as 
`
<function set_session at 0x7f88fde5dae8>
`

**Comment by rafikg** [comment]
I have the same problem on Ubuntu. Did you resolve it?

**Comment by tonmoyborah** [comment]
I tried this and my keras is using TF backend but I still get this exception. 
TF 1.5
Keras 2.1.6

**Comment by JanderHungrige** [comment]
I  am using TF2.0.0a I have a similar issue with `get_session()`. I posted it also on [stackoverflow](https://stackoverflow.com/questions/56646940/how-to-properly-saving-loaded-h5-model-to-pb-with-tf2)

**Comment by balu-ce** [comment]
try to replace **tf.keras.backend.get_session()** with **tf.compat.v1.keras.backend.get_session()**

**Comment by stenpiren** [comment]
For tensorflow prior to version 2, do:
```from tensorflow.compat.v1.keras import backend as K```
```K.set_session()```

**Comment by yugyesh** [comment]
For me, the error gets solved using
`from tensorflow.python.keras import backend as K` 
instead of 
`from keras import backend as K`
I was using tf-2 in anaconda

**Comment by shrikantpardhi** [comment]
> For tensorflow prior to version 2, do:
> `from tensorflow.compat.v1.keras import backend as K`
> `K.set_session()`

This works fine with TF v2.x,

**Comment by murph-1999** [comment]
> > For tensorflow prior to version 2, do:
> > `from tensorflow.compat.v1.keras import backend as K`
> > `K.set_session()`
> 
> This works fine with TF v2.x,

I tried this way, but it does not work.

**Comment by murph-1999** [comment]
> from tensorflow.python.keras import backend as K

you are right!

**Comment by cooLBooy1128** [comment]
> > from tensorflow.python.keras import backend as K
> 
> you are right!

nice! Thank you!

**Comment by RAOMMA** [comment]
> For me, the error gets solved using `from tensorflow.python.keras import backend as K` instead of `from keras import backend as K` I was using tf-2 in anaconda

This worked for me too on ubuntu
