### ISSUE TITLE
Confusing documentation for implementing new distributions

### ISSUE THREAD

**Issue by aksarkar** [blei-lab/edward#755]
According to http://edwardlib.org/api/model-development, ```CustomRandomVariable``` should multiple inherit from ```ed.models.RandomVariable``` and ```tf.contrib.distributions.Distribution```. 

This suggests that any subclass-specific implementations of the Tensorflow Distribution API (e.g. mean, variance) should also go in ```CustomRandomVariable```.

However, implementing it like this causes an exception in ```ed.util.copy``` (called from ```ed.KLqp```) because ```kwargs``` for ```Distribution``` end up getting passed into the ```CustomRandomVariable.__init__```.

The confusing part is that ```ed.models.Empirical``` and ```ed.models.PointMass``` (referred to in the docs) aren't actually implemented like this. Instead, ```distribution_X``` implements the Tensorflow Distribution API and a wrapper ```X``` exposes it to Edward.

The tricky part to figure out (I used pdb to step through ```ed.models.Normal.__init__```) is that ```ed.models.RandomVariable.__init__``` removes Edward specific arguments (like ```value```) from ```kwargs```, but not the Tensorflow specific arguments. So we can't just put all the keyword arguments for both ```RandomVariable``` and ```Distribution``` in the call to ```super``` in the snippet from the docs (assuming that each type takes whichever ```kwargs``` it needs and passes the rest up the inheritance chain). Instead, we really do need to write two classes, as is done in the existing types.

Perhaps better would be to go through the ```Empirical``` implementation in the docs.

**Comment by dustinvtran** [comment]
That's a great point. Would love help to improve the docs there if you're interested.

**Comment by davharris** [comment]
In the interest of cross-referencing: 

This issue is referenced in [a Discourse thread](https://discourse.edwardlib.org/t/simple-wrapper-custom-variable/367/4?u=davharris) that includes a more up-to-date example.
