### ISSUE TITLE
 cannot import name 'inference_new' . Unable to import new inference method .

### ISSUE THREAD

**Issue by wset2** [blei-lab/edward#766]
Hi

I am writing a new inference method and saved it as 'inference_new.py' under edward.inferences with class Inference_New . I have added

`from edward.inferences import Inference_New` to the __init__.py file under edward and

`from edward.inferences.inference_new import *` and 
`_allowed_symbols = [ 'Inference_New' ] ` to the __init__.py file under edward.inferences

I attempted to use this new class in the supervised regression notebook example instead of KLqp but I am unable to import the new class .

`ImportError                               Traceback (most recent call last)
<ipython-input-2-ce017d0c6494> in <module>()
----> 1 from edward.inferences import BB_alpha

ImportError: cannot import name 'BB_alpha'`

Sorry if this is a basic question.

**Comment by dustinvtran** [comment]
Did you also add it to the allowed symbols in `edward/__init__.py`? You can also look at where another class, e.g., [SGLD is included in the code base](https://github.com/blei-lab/edward/search?utf8=✓&q=sgld&type=).

**Comment by wset2** [comment]
Yes I have @dustinvtran , but I am still only able to import original classes such as KLpq and KLqp and not any new classes created. Could this be a problem with my PYTHONPATH?

**Comment by dustinvtran** [comment]
You should check that you pip installed Edward locally to the directory you're working in. `pip list | grep edward` should show something like `edward (1.3.3, /Users/dvt/Dropbox/ssh/edward)`.

**Comment by wset2** [comment]
I pip installed Edward locally but I did ```pip install edward``` instead of ```pip install -e edward``` . It is working fine now. Thank you
