### ISSUE TITLE
Categorical Variational

### ISSUE THREAD

**Issue by abojchevski** [blei-lab/edward#77]
Any estimation oh how hard it would be to extend the current variationals and add a Categorical one?

I tried myself, but not sure if I am on the right path, might be possible with a softmax mapping or am I missing something?

**Comment by dustinvtran** [comment]
Not difficult but because categorical/multinomial is a multivariate distribution the dimension and parameter storage is slightly more complicated, c.f., the implementation of the Dirichlet. I'll work on a multinomial version right now.

**Comment by abojchevski** [comment]
With the current implementation of the Multinomial variational I am getting
```
ValueError: concat_dim is out of range (values rank = 1)
```
in `def mapping(self, x):` during the `tf.concat` operation.

In any case I don't think the mapping is correct. 

To map a `K-1` real vector (with possibly negative values), to the standard K simplex (values sum up to 1), one needs the following transformation:

```
K = 3
num_factors = 5


def transform(pi):
    with tf.Session():
        eq = -np.log(K - 1 - np.arange(K - 1))
        z = tf.sigmoid(eq + pi).eval()
        pil = np.column_stack((z, np.ones(num_factors)))
        piu = np.column_stack((np.ones(num_factors), 1 - z))
        S = np.cumprod(piu, axis=1)
        x = S * pil

        return x


example = np.array([[-0.3, 5] for i in range(num_factors)])
print(transform(example))
```

Sorry the example is mostly numpy, I'm not proficient in tensorflow yet.

**Comment by dustinvtran** [comment]
Ah, yes my mistake. For some reason I had presumed that squashing them down to `[0,1]` would already constrained them to sum to less than 1.. I will fix that now. 

re:error. It sounds like the two values that are concatenated are not at least two-dimensional. I'll fix the above issue and that may already solve the problem.

**Comment by dustinvtran** [comment]
Fixed in 5dcb2af57af3d5c23bbfcc0d630e998a74d23cb6. I ended up having to write a `cumprod` in TensorFlow.

```{Python}
K = 3
num_factors = 5

def transform(pi):
    with tf.Session():
        eq = -np.log(K - 1 - np.arange(K - 1))
        z = tf.sigmoid(eq + pi).eval()
        pil = np.column_stack((z, np.ones(num_factors)))
        piu = np.column_stack((np.ones(num_factors), 1 - z))
        S = np.cumprod(piu, axis=1)
        x = S * pil
        return x

example = np.array([[-0.3, 5] for i in range(num_factors)])
print(transform(example))

sess = tf.Session()

def transform(pi):
    eq = -tf.log(tf.cast(K - 1 - tf.range(K-1), dtype=tf.float32))
    z = tf.sigmoid(eq + pi)
    pil = tf.concat(1, [z, tf.ones([num_factors, 1])])
    piu = tf.concat(1, [tf.ones([num_factors, 1]), 1.0 - z])
    # cumulative product along 1st axis
    S = tf.pack([cumprod(piu_x) for piu_x in tf.unpack(piu)])
    return [S * pil]

example = np.array([[-0.3, 5.0] for i in range(num_factors)])
print(sess.run(transform(example)[0]))
```

**Comment by abojchevski** [comment]
Nice job. Surprising that tensorflow does't have a cumprod already.

Just for reference this is the backward stick breaking transformation. The above code snipped was based on pymc3 implementation which was in turn based on STAN implementation. 

You can keep in mind there is also a forward transformation `Transforms K dimensional simplex space (values in [0,1] and sum to 1) to K - 1 vector of real values` if it might be useful at some point.

**Comment by abojchevski** [comment]
Additioanly you have to change:
this:
```
 eq = -tf.log(tf.cast(K - 1 - tf.range(K-1), dtype=tf.float32))
```

to:
```
 eq = -tf.log(tf.cast(self.K - 1 - tf.range(self.K-1), dtype=tf.float32))
```

in your variational class. Just add `self.` in front of the K.

**Comment by dustinvtran** [comment]
Done (61781c430d8182765dea09ba37692ee0b985105e). Thanks for the reference! Yes, it's great that we ultimately used Stan's transformation. :)
