### ISSUE TITLE
Automated VI infers against original variable.

### ISSUE THREAD

**Issue by cshenton** [blei-lab/edward#785]
From this [discourse thread](https://discourse.edwardlib.org/t/bug-in-automated-transformations-for-variables-with-simplex-support/440).

It appears that the automatic transform is inferring against the original prior (in the constrained space), rather than a transformation of the prior in unconstrained space. This will fail silently if dimensions match (i.e. positive, interval), but fails for simplex constraints.

```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import edward as ed
import tensorflow as tf

from edward.models import Dirichlet

alpha = [1.0, 2.0, 3.0]
phi = Dirichlet(alpha)

inference = ed.KLqp([phi])
qphi = inference.latent_vars[phi]
inference.run()
```

> ValueError: Dimensions must be equal, but are 3 and 4 for ‘inference/sample/Dirichlet/log_prob/mul’ (op: ‘Mul’) with input shapes: [3], [4].

From a quick look at the automated transforms implementation, this is due to the fact no new priors are created, the original constrained variable appears to be matched with an unconstrained variational model.

**Comment by dustinvtran** [comment]
Fixed in https://github.com/blei-lab/edward/pull/808.
