### ISSUE TITLE
Progress bar encoding error - Windows

### ISSUE THREAD

**Issue by aornugent** [blei-lab/edward#790]
Total edge case, but this:
https://github.com/blei-lab/edward/blob/0a995aec7a757812c59246b77452ad0b4f26ce64/edward/util/progbar.py#L83

causes edward to crash on my system:

```
UnicodeEncodeError: 'charmap' codec can't encode character '\u2588' in position 17: character maps to <undefined>
```

Switching to any other character resolves the issue.

**Comment by dustinvtran** [comment]
Does a simple try/except, whose except block swaps the character with a more compatible character work?

**Comment by theSage21** [comment]
@aornugent could you specify a character that works?

**Comment by aornugent** [comment]
I went with '+'.

**Comment by dustinvtran** [comment]
#692. This fix is still up for grabs if anyone's interested. Should be a 3-5 line addition for the try/except block.
