### ISSUE TITLE
Variable Scoping Problem

### ISSUE THREAD

**Issue by alirezazareian** [blei-lab/edward#797]
This line of code in variational inference creates a variable scope with a non-deterministic name. Hence, it makes it hard to restore checkpoints since optimizer variable names in saved model and new model don't match. There is no need to call the variable_scope with default_name. You can simply use a deterministic name for the scope and take it from the user as an optional argument with default value.

https://github.com/blei-lab/edward/blob/081ea532a982e6d2c88da25d6e2527f6a66f09ab/edward/inferences/variational_inference.py#L118

**Comment by dustinvtran** [comment]
IIRC unlike other variable scopes in Inference, this uses `default_name` because you might call inference multiple times, and they should each have a unique variable scope. Happy to consider alternative solutions.

Checkpointing should be fine if inference is called within the same order, which it would in a script called multiple times. Can you provide an example?

**Comment by alirezazareian** [comment]
When I create a model and its inference optimizer, and when the optimizer is something like Adam which creates its own variables, it makes them in a namescope named optimizer_<some_long_number>. Then I train it and save as a checkpoint. Next time when I create the model using the same function (which creates the computational graph in the same order), the optimizer variables are created in a namescope named optimizer_<some_other_number>. Hence, when I try to load the checkpoint, it will not work, unless I manually match the names by providing a dictionary.

**Comment by dustinvtran** [comment]
Are you using the latest Edward version? That sounds like an older version, e.g., [1.3.2](https://github.com/blei-lab/edward/blob/4a5ae1bb99bfc851e826912c156ea66aee1e262b/edward/inferences/variational_inference.py) which indexed variable names via things like `optimizer_ + str(id(self))` which does vary across script calls.

**Comment by dustinvtran** [comment]
Closing as issue was with older Edward version.
