### ISSUE TITLE
add distribution objects

### ISSUE THREAD

**Issue by dustinvtran** [blei-lab/edward#80]
Any distribution available in `edward.stats` should have a corresponding distribution object that is also available in `edward.models`.

Discrete
+ [x] Bernoulli
+ [ ] Binomial
+ [x] Multinomial (assume single trial, i.e., `n=1` when sampling and calculating density)
+ [ ] Poisson
+ [ ] Geometric
+ [ ] Negative Binomial
+ [x] Point mass

Continuous
+ [ ] Uniform
+ [ ] Multivariate Normal
+ [ ] Student-t (with mean and scale parameters)
+ [ ] Gamma
+ [x] Inverse Gamma
+ [ ] Exponential
+ [x] Beta
+ [x] Dirichlet
+ [ ] Log-Normal
+ [ ] Chi-squared

See also #77.

**Comment by altosaar** [comment]
Should we stick to tf.contrib.distributions and submit PRs there?

**Comment by dustinvtran** [comment]
(looping in @heywhoah. I'm also planning to discuss this next week in the Bayesflow meeting.)

Yeah I was thinking about this recently. The distribution objects in our library and the distribution objects in `tf.contrib.distributions` are very similar. There are a few things to address.

1. The two distribution objects have slightly different desired behavior. For example, the inputs/outputs to our log density method is different. In another branch, we are adding arithmetic so that we can treat the distribution objects as if they were any other tensor, and that we can also bind them to realizations. This will make our objects inbetween distribution objects in `tf.contrib.distributions` and distribution tensors in `tf.contrib.bayesflow.scg`.

  __Solution.__ We can use `tf.contrib.distributions` as the base, and have our distribution objects be a wrapper around it. This enables higher-level methods  without having to reinvent the wheel with regards to primitive operations. It is analogous to how `tf.contrib.bayesflow.scg` builds on top of `tf.contrib.distributions`. 

  We will follow TensorFlow's standards regarding input/output behavior, and also style guidelines. This will make it easier to submit pull requests as we develop primitive operations that are not available in `tf.contrib.distributions` that we need. (We have many of these.)
2. Experimental features in TensorFlow. We only want to have a stable version of TensorFlow as a dependency, and not require features from `tf.contrib` which is bound to change.

  __Solution.__ Perhaps we should have a static version of `tf.contrib.distributions` natively in Edward. That is, we copy and paste the whole `tf.contrib.distributions` as a subdirectory in Edward?

**Comment by dustinvtran** [comment]
Following #237, we simply use whichever random variables are available in `tf.contrib.distributions`.
