### ISSUE TITLE
cannot import name 'NOT_REPARAMETERIZED'. Your TensorFlow version is not supported.

### ISSUE THREAD

**Issue by sachinjm** [blei-lab/edward#801]
I am trying to run bayesian_nn.py from examples folder of edward, but getting following error 

cannot import name 'NOT_REPARAMETERIZED'. Your TensorFlow version is not supported.

TF version is 1.0.1

**Comment by dustinvtran** [comment]
Says as described. Edward requires TF 1.2.0+.

https://github.com/blei-lab/edward/blob/master/setup.py#L18
