### ISSUE TITLE
DRY __init__ methods of `VariationalInference` children in inferences/klqp.py

### ISSUE THREAD

**Issue by cavaunpeu** [blei-lab/edward#815]
@dustinvtran 

Is this a thing we'd like to do? At present, this is duplicated ~7 times.

**Comment by dustinvtran** [comment]
Do you mean the boilerplate in `__init__`? We could abstract this, although I do like the flattened structure where it's easy to stare at one KLqp class without having to understand the others.

**Comment by cavaunpeu** [comment]
Good point, but it is ~15 lines of code, and repeated verbatim 7x. Anyways, just something that jumped out at me. Up to you.

**Comment by dustinvtran** [comment]
Closing for now. A few others in Google Research and I are working on an Edward 2.0 (public branch should be available shortly). Part of it overhauls the inference structure to remove the OO entirely, so no boilerplate `__init__`.

**Comment by cavaunpeu** [comment]
👍
