### ISSUE TITLE
VI descriptions are not accurate

### ISSUE THREAD

**Issue by samuela** [blei-lab/edward#838]
On http://edwardlib.org/api/ed/inferences :

![screen shot 2018-01-29 at 5 59 42 pm](https://user-images.githubusercontent.com/226872/35544276-6096a876-051e-11e8-9450-bec30775daf3.png)

**Comment by dustinvtran** [comment]
The single-line VI description is hard to be more accurate about. Their docstrings if you click them have more accurate info. Open to suggestions on how to make this more fine-grained.

**Comment by samuela** [comment]
Ah I see... I didn't realize this was constrained by the 80 character line. 

On first read I surmised that "Variational inference with KL divergence" referred to using an analytic KL term as opposed to entropy, etc. I assume that they're instead referring to optimizing over the KL metric in the first place. That makes sense.
