### ISSUE TITLE
Installation: "No matching distribution found for tensorflow>=0.7.0" but there is

### ISSUE THREAD

**Issue by ueser** [blei-lab/edward#84]
When installing (on MacOS X) under virtual environment, I get this error:

 (tfvenv)Projects umut$ pip install edward
Collecting edward
  Using cached edward-1.0.4-py2-none-any.whl
Collecting tensorflow>=0.7.0 (from edward)
  Could not find a version that satisfies the requirement tensorflow>=0.7.0 (from edward) (from versions: )
No matching distribution found for tensorflow>=0.7.0 (from edward)

However, I have tensorflow 0.8.0:

(tfvenv)Projects umut$ python -c "import tensorflow; print(tensorflow.**version**);"
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.7.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.7.5.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.7.5.dylib locally
0.8.0

**Comment by dustinvtran** [comment]
These references seem useful:

+ http://stackoverflow.com/questions/36490849/installing-prettytensor-for-tensorflow-not-working-on-osx
+ https://github.com/tensorflow/tensorflow/issues/1244

**Comment by thomasklau** [comment]
For some reason, setuptools wasn't able to find my tensorflow version (0.9) when 'tensorflow>=0.10.0rc0' was in the required package. It worked fine for me when I changed it to 'tensorflow>=0.10.0' - is this a bug?

**Comment by thomasklau** [comment]
'>=0.9.0rc0' also works fine - isn't >=0.9 required anways as it says here? 

http://edwardlib.org/troubleshooting
https://github.com/blei-lab/edward/blob/master/setup.py

**Comment by thomasklau** [comment]
For some reason, pip install installed tensorflow0.9 on my computer. I was able to fix this by checking my tensorflow version with 'pip show tensorflow' and then uninstalling and installing again.

**Comment by kirk86** [comment]
Does `edward` require `prettytensor`? Other than that I have the same issue on OSx with conda and latest `tensorflow` `0.12.1`

**Comment by stonebig** [comment]
it's witten in setup.py:
````
 tensorflow>=0.11.0rc0,!=0.12.0rc0,!=0.12.0rc1,!=0.12.0',!=0.12.1',
````

Edward currently support only Tensorflow-0.11.something

**Comment by kirk86** [comment]
@stonebig Oh, my bad, I missed that. Since this issue was raised by someone else I'm leaving it as it is. Thanks for the heads up.
