### ISSUE TITLE
Bayesian Neural Networks using R. Neal's code

### ISSUE THREAD

**Issue by berceanu** [blei-lab/edward#845]
I noticed the tutorial on [Bayesian Neural Networks](http://edwardlib.org/tutorials/bayesian-neural-network) cites R. Neal's book. I am wondering if `Edward` wrapped (or reimplemented) his [`C` software](http://www.cs.toronto.edu/~radford/fbm.software.html) for _Flexible Bayesian Modeling and Markov Chain Sampling_. I want to to use his code from `Python`, either in `Edward` or [`PyMC3`](https://github.com/pymc-devs/pymc3)/[`Stan`](https://github.com/stan-dev/stan).

**Comment by dustinvtran** [comment]
We didn't transfer his code to Edward. It does reimplement the core algorithm though (namely, HMC).

**Comment by berceanu** [comment]
So there is feature parity between his code and `Edward`?
