### ISSUE TITLE
analytic KL for more models (w/ conjugate priors)

### ISSUE THREAD

**Issue by mariru** [blei-lab/edward#97]

**Comment by dustinvtran** [comment]
her'e a sequence of extensions:

+ from standard normal priors to non-standard normal priors
+ conjugate priors whose KL divergence is analytically tractable
+ leverage only portions of the probability model's prior that enables an analytically tractable KL, e.g., conjugate prior for one components, non-conjugate for another component

**Comment by altosaar** [comment]
there is now a KL registration mechanism for tf.contrib.distributions; here's an example: 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/distributions/python/ops/normal.py#L332

let me know if you run into issues implementing these!

**Comment by dustinvtran** [comment]
See comment in https://github.com/blei-lab/edward/issues/80#issuecomment-229134940. I think the same holds, i.e., we can leverage whatever is already available in `tf.contrib.distributions` and build on top of it. Whenever the feature is useful natively in `tf.contrib.distributions` we will submit a pull request.

**Comment by dustinvtran** [comment]
Fixed in #504. However, note it is not available in `ed.KLqp` yet; see #456.
