### ISSUE TITLE
documentation/tutorial on optimization based inference techniques

### ISSUE THREAD

**Issue by mariru** [blei-lab/edward#98]
possible topics:
 - Infernce (what does it mean to do inference)
 - Variational Inferece
 - ADVI
 - BBVI
 - Score function gradient
 - Reparametrization gradient

**Comment by dustinvtran** [comment]
I added [importance-weighted variational inference](https://github.com/blei-lab/edward/blob/master/examples/iwvi.py) as an example script. This will do for now until we develop a full-blown tutorial in the coming weeks.
