### ISSUE TITLE
move to a new documentation interface

### ISSUE THREAD

**Issue by dustinvtran** [blei-lab/edward#99]
I think it's time we start moving away from Wiki pages toward a solution like Sphinx or mkdocs. Things like #95, #96, #98 clearly motivate this. Here are some thoughts off the top of my head:

+ clean, intuitive interface, with black and white (and maybe blue)
+ two columns, with one column being a table of contents of links
+ homepage being just like the `README.md`
+ a section on getting started, which runs through a very simple example, and goes briefly through the main components and features (similar to current wiki pages)
+ a section on tutorials, which teach various concepts such as a specific model, stochastic variational inference, how to use posterior predictive checks, etc.; maybe it should be a static page with embedded python, and there should be a ipython notebook link to just the raw code (related to #35)
+ a section describing each module in Edward in detail, including all of their features and how to access them
+ section on various other pages, e.g., developer process, design and philosophy, references, possibly a standalone section on specific things that pertain to using Edward for research
+ bonus points if it can be easily turned into a pdf as a booklet

Here are some documentation examples that can be good reference tools:
+ [Leaf](http://autumnai.com/leaf/book/leaf.html)
+ [Rust](https://www.rust-lang.org/documentation.html)
+ [Keras](http://keras.io)
+ [GPy's tutorial notebooks](http://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/index.ipynb)
+ [Caffe's tutorial notebooks](http://caffe.berkeleyvision.org)
+ [Julia](http://docs.julialang.org/en/release-0.4/)
+ [TensorFlow](https://www.tensorflow.org)
+ [Advanced R](http://adv-r.had.co.nz)
+ [Numpy](http://docs.scipy.org/doc/)

Thoughts appreciated.

**Comment by mariru** [comment]
I created a branch documentation/sphinx where I'll experiment with generating a documentation using sphinx http://www.sphinx-doc.org/en/stable/

**Comment by dustinvtran** [comment]
Awesome, thanks @mariru
